CREATE OR REPLACE VIEW {{schema}}.clickstream_ods_flattened_view AS
SELECT 
  e.event_date as event_date,
  e.event_name as event_name,
  e.event_id as event_id,
  e.event_bundle_sequence_id as event_bundle_sequence_id,
  event_params.key,
  event_params.value.double_value::DOUBLE PRECISION,
  event_params.value.float_value::DOUBLE PRECISION,
  event_params.value.int_value::int,
  event_params.value.string_value::varchar,
  e.event_previous_timestamp as event_previous_timestamp,
  e.event_server_timestamp_offset as event_server_timestamp_offset,
  e.event_timestamp as event_timestamp,
  e.ingest_timestamp as ingest_timestamp,
  e.event_value_in_usd as event_value_in_usd,
  e.app_info.app_id as app_info_app_id ,
  e.app_info.version as app_info_version,
  e.device.browser as device_browser,
  e.device.browser_version as device_browser_version,
  e.device.language as device_language ,
  e.device.mobile_brand_name as device_mobile_brand_name,
  e.device.mobile_model_name as device_mobile_model_name,
  e.device.operating_system as device_operating_system,
  e.device.time_zone_offset_seconds as device_time_zone_offset_seconds,
  e.device.web_info as device_web_info,
  e.geo.continent as geo_continent,
  e.geo.country as geo_country,
  e.geo.city as geo_city,
  e.platform as platform,
  e.project_id as project_id,
  e.traffic_source.name as traffic_source_name,
  e.traffic_source.meidum as traffic_source_meidum,
  e.traffic_source.source as traffic_source_source,
  e.user_first_touch_timestamp as user_first_touch_timestamp,
  e.user_id as user_id,
  e.user_ltv as user_ltv,
  e.user_pseudo_id as user_pseudo_id
FROM {{schema}}.{{table_ods_events}} e, e.event_params as event_params