#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

OWN_FILENAME="$(basename $0)"
LAMBDA_EXTENSION_NAME="$OWN_FILENAME" # (external) extension name has to match the filename
echo "[${LAMBDA_EXTENSION_NAME}] Initialization"

ARCH=`uname -m`
CMD="/opt/libs/${ARCH}/lambda-adapter"

echo "[${LAMBDA_EXTENSION_NAME}] Running on ${ARCH}, forwarding to corresponding adapter ${CMD}"

"$CMD"
