/**
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
 *  with the License. A copy of the License is located at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
 *  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
 *  and limitations under the License.
 */

export const CATEGORY_RULE = [
  {
    url: '1.cz',
    source: '1.cz',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: '360.cn',
    source: '360',
    category: 'Search',
    params: [],
  },
  {
    url: '43things.com',
    source: '43things',
    category: 'Social',
    params: [],
  },
  {
    url: '51.com',
    source: '51',
    category: 'Social',
    params: [],
  },
  {
    url: '5ch.net',
    source: '5ch',
    category: 'Social',
    params: [],
  },
  {
    url: 'aax-us-east.amazon-adsystem.com',
    source: 'aax-us-east.amazon-adsystem',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'aax.amazon-adsystem.com',
    source: 'aax.amazon-adsystem',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'abcsok.no',
    source: 'ABCs\u00f8k',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'academia.edu',
    source: 'academia',
    category: 'Social',
    params: [],
  },
  {
    url: 'activerain.com',
    source: 'activerain',
    category: 'Social',
    params: [],
  },
  {
    url: 'activeworlds.com',
    source: 'activeworlds',
    category: 'Social',
    params: [],
  },
  {
    url: 'addthis.com',
    source: 'addthis',
    category: 'Social',
    params: [],
  },
  {
    url: 'airg.ca',
    source: 'airg',
    category: 'Social',
    params: [],
  },
  {
    url: 'alexa.com',
    source: 'Alexa',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'alibaba.com',
    source: 'alibaba',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'alice.com',
    source: 'alice',
    category: 'Search',
    params: [],
  },
  {
    url: 'all.by',
    source: 'All.by',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'allnurses.com',
    source: 'allnurses',
    category: 'Social',
    params: [],
  },
  {
    url: 'allrecipes.com',
    source: 'allrecipes',
    category: 'Social',
    params: [],
  },
  {
    url: 'alohafind.com',
    source: 'AlohaFind',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'altavista.com',
    source: 'AltaVista',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'altavista.de',
    source: 'AltaVista',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'altavista.fr',
    source: 'AltaVista',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'alumniclass.com',
    source: 'alumniclass',
    category: 'Social',
    params: [],
  },
  {
    url: 'amazon.co.uk',
    source: 'amazon',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'amazon.com',
    source: 'amazon',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'ameba.jp',
    source: 'ameba',
    category: 'Social',
    params: [],
  },
  {
    url: 'ameblo.jp',
    source: 'ameblo',
    category: 'Social',
    params: [],
  },
  {
    url: 'americantowns.com',
    source: 'americantowns',
    category: 'Social',
    params: [],
  },
  {
    url: 'amp.reddit.com',
    source: 'amp.reddit',
    category: 'Social',
    params: [],
  },
  {
    url: 'ancestry.com',
    source: 'ancestry',
    category: 'Social',
    params: [],
  },
  {
    url: 'anobii.com',
    source: 'anobii',
    category: 'Social',
    params: [],
  },
  {
    url: 'answerbag.com',
    source: 'answerbag',
    category: 'Social',
    params: [],
  },
  {
    url: 'answers.yahoo.com',
    source: 'answers.yahoo',
    category: 'Social',
    params: [],
  },
  {
    url: 'aol.com',
    source: 'aol',
    category: 'Search',
    params: [],
  },
  {
    url: 'aolanswers.com',
    source: 'aolanswers',
    category: 'Social',
    params: [],
  },
  {
    url: 'apps.facebook.com',
    source: 'apps.facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'apps.shopify.com',
    source: 'apps.shopify',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'ar.pinterest.com',
    source: 'ar.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'ar.search.yahoo.com',
    source: 'ar.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'ar.zapmeta.com',
    source: 'Zapmeta',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'arama.com',
    source: 'Arama',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'ariadna.elmundo.es',
    source: 'El Mundo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'artstation.com',
    source: 'artstation',
    category: 'Social',
    params: [],
  },
  {
    url: 'ask.com',
    source: 'Ask',
    category: 'Search',
    params: [
      'ask',
      'q',
      'searchfor',
    ],
  },
  {
    url: 'askubuntu.com',
    source: 'askubuntu',
    category: 'Social',
    params: [],
  },
  {
    url: 'asmallworld.com',
    source: 'asmallworld',
    category: 'Social',
    params: [],
  },
  {
    url: 'at.search.yahoo.com',
    source: 'at.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'athlinks.com',
    source: 'athlinks',
    category: 'Social',
    params: [],
  },
  {
    url: 'au.search.yahoo.com',
    source: 'au.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'au.zapmeta.com',
    source: 'Zapmeta',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'avg.com',
    source: 'avg',
    category: 'Search',
    params: [],
  },
  {
    url: 'avira.search.ask.com',
    source: 'Ask',
    category: 'Search',
    params: [
      'ask',
      'q',
      'searchfor',
    ],
  },
  {
    url: 'away.vk.com',
    source: 'away.vk',
    category: 'Social',
    params: [],
  },
  {
    url: 'awe.sm',
    source: 'awe',
    category: 'Social',
    params: [],
  },
  {
    url: 'b.hatena.ne.jp',
    source: 'b.hatena',
    category: 'Social',
    params: [],
  },
  {
    url: 'baby-gaga.com',
    source: 'baby-gaga',
    category: 'Social',
    params: [],
  },
  {
    url: 'babyblog.ru',
    source: 'babyblog',
    category: 'Social',
    params: [],
  },
  {
    url: 'badoo.com',
    source: 'Badoo',
    category: 'Social',
    params: [],
  },
  {
    url: 'baidu.com',
    source: 'Baidu',
    category: 'Search',
    params: [
      'kw',
      'wd',
      'word',
    ],
  },
  {
    url: 'be-fr.altavista.com',
    source: 'AltaVista',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'be-nl.altavista.com',
    source: 'AltaVista',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'bebo.com',
    source: 'Bebo',
    category: 'Social',
    params: [],
  },
  {
    url: 'beforeitsnews.com',
    source: 'beforeitsnews',
    category: 'Social',
    params: [],
  },
  {
    url: 'bharatstudent.com',
    source: 'bharatstudent',
    category: 'Social',
    params: [],
  },
  {
    url: 'biglobe.co.jp',
    source: 'biglobe',
    category: 'Search',
    params: [],
  },
  {
    url: 'biglobe.ne.jp',
    source: 'biglobe',
    category: 'Search',
    params: [],
  },
  {
    url: 'biip.no',
    source: 'biip',
    category: 'Social',
    params: [],
  },
  {
    url: 'bing.com',
    source: 'Bing',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'bing.com/images/search',
    source: 'Bing Images',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'biswap.org',
    source: 'biswap',
    category: 'Social',
    params: [],
  },
  {
    url: 'bit.ly',
    source: 'bit',
    category: 'Social',
    params: [],
  },
  {
    url: 'bitcoinhackers.org',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'blackcareernetwork.com',
    source: 'blackcareernetwork',
    category: 'Social',
    params: [],
  },
  {
    url: 'blackplanet.com',
    source: 'blackplanet',
    category: 'Social',
    params: [],
  },
  {
    url: 'blip.fm',
    source: 'blip',
    category: 'Social',
    params: [],
  },
  {
    url: 'blog.com',
    source: 'blog',
    category: 'Social',
    params: [],
  },
  {
    url: 'blog.feedspot.com',
    source: 'blog.feedspot',
    category: 'Social',
    params: [],
  },
  {
    url: 'blog.goo.ne.jp',
    source: 'blog.goo',
    category: 'Social',
    params: [],
  },
  {
    url: 'blog.naver.com',
    source: 'blog.naver',
    category: 'Social',
    params: [],
  },
  {
    url: 'blog.twitch.tv',
    source: 'blog.twitch',
    category: 'Video',
    params: [],
  },
  {
    url: 'blog.yahoo.co.jp',
    source: 'blog.yahoo',
    category: 'Social',
    params: [],
  },
  {
    url: 'blogg.no',
    source: 'blogg',
    category: 'Social',
    params: [],
  },
  {
    url: 'bloggang.com',
    source: 'bloggang',
    category: 'Social',
    params: [],
  },
  {
    url: 'blogger.com',
    source: 'blogger',
    category: 'Social',
    params: [],
  },
  {
    url: 'blogher.com',
    source: 'blogher',
    category: 'Social',
    params: [],
  },
  {
    url: 'bloglines.com',
    source: 'bloglines',
    category: 'Social',
    params: [],
  },
  {
    url: 'blogs.com',
    source: 'blogs',
    category: 'Social',
    params: [],
  },
  {
    url: 'blogsome.com',
    source: 'blogsome',
    category: 'Social',
    params: [],
  },
  {
    url: 'blogspot.com',
    source: 'blogspot',
    category: 'Social',
    params: [],
  },
  {
    url: 'blogster.com',
    source: 'blogster',
    category: 'Social',
    params: [],
  },
  {
    url: 'blurtit.com',
    source: 'blurtit',
    category: 'Social',
    params: [],
  },
  {
    url: 'bookmarks.yahoo.co.jp',
    source: 'bookmarks.yahoo',
    category: 'Social',
    params: [],
  },
  {
    url: 'bookmarks.yahoo.com',
    source: 'bookmarks.yahoo',
    category: 'Social',
    params: [],
  },
  {
    url: 'botsin.space',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'br.pinterest.com',
    source: 'br.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'br.search.yahoo.com',
    source: 'br.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'brightkite.com',
    source: 'brightkite',
    category: 'Social',
    params: [],
  },
  {
    url: 'brizzly.com',
    source: 'brizzly',
    category: 'Social',
    params: [],
  },
  {
    url: 'bsky.app',
    source: 'Bluesky',
    category: 'Social',
    params: [],
  },
  {
    url: 'busca.uol.com.br',
    source: 'uol.com.br',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'buscador.terra.cl',
    source: 'Terra',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'buscador.terra.com.br',
    source: 'Terra',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'buscador.terra.es',
    source: 'Terra',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'business.facebook.com',
    source: 'business.facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'buzzfeed.com',
    source: 'buzzfeed',
    category: 'Social',
    params: [],
  },
  {
    url: 'buzznet.com',
    source: 'Buzznet',
    category: 'Social',
    params: [],
  },
  {
    url: 'ca.search.yahoo.com',
    source: 'ca.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'ca.zapmeta.com',
    source: 'Zapmeta',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'cade.images.yahoo.com',
    source: 'Yahoo! Images',
    category: 'Search',
    params: [
      'p',
      'va',
    ],
  },
  {
    url: 'cade.yahoo.com',
    source: 'Yahoo!',
    category: 'Search',
    params: [
      'p',
      'q',
    ],
  },
  {
    url: 'cafe.naver.com',
    source: 'cafe.naver',
    category: 'Social',
    params: [],
  },
  {
    url: 'cafemom.com',
    source: 'cafemom',
    category: 'Social',
    params: [],
  },
  {
    url: 'camospace.com',
    source: 'camospace',
    category: 'Social',
    params: [],
  },
  {
    url: 'canalblog.com',
    source: 'canalblog',
    category: 'Social',
    params: [],
  },
  {
    url: 'care.com',
    source: 'care',
    category: 'Social',
    params: [],
  },
  {
    url: 'care2.com',
    source: 'care2',
    category: 'Social',
    params: [],
  },
  {
    url: 'caringbridge.org',
    source: 'caringbridge',
    category: 'Social',
    params: [],
  },
  {
    url: 'catster.com',
    source: 'catster',
    category: 'Social',
    params: [],
  },
  {
    url: 'cbnt.io',
    source: 'cbnt',
    category: 'Social',
    params: [],
  },
  {
    url: 'cc.bingj.com',
    source: 'Bing',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'cellufun.com',
    source: 'cellufun',
    category: 'Social',
    params: [],
  },
  {
    url: 'centerblog.net',
    source: 'centerblog',
    category: 'Social',
    params: [],
  },
  {
    url: 'centrum.cz',
    source: 'centrum',
    category: 'Search',
    params: [],
  },
  {
    url: 'cgi.search.biglobe.ne.jp',
    source: 'Biglobe',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'ch.search.yahoo.com',
    source: 'ch.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'chaos.social',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'chat.zalo.me',
    source: 'chat.zalo',
    category: 'Social',
    params: [],
  },
  {
    url: 'checkout.shopify.com',
    source: 'checkout.shopify',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'checkout.stripe.com',
    source: 'checkout.stripe',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'chegg.com',
    source: 'chegg',
    category: 'Social',
    params: [],
  },
  {
    url: 'chicagonow.com',
    source: 'chicagonow',
    category: 'Social',
    params: [],
  },
  {
    url: 'chiebukuro.yahoo.co.jp',
    source: 'chiebukuro.yahoo',
    category: 'Social',
    params: [],
  },
  {
    url: 'cl.search.yahoo.com',
    source: 'cl.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'claro-search.com',
    source: 'Claro Search',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'class.hit-parade.com',
    source: 'Hit-Parade',
    category: 'Search',
    params: [
      'p7',
    ],
  },
  {
    url: 'classmates.com',
    source: 'Classmates.com',
    category: 'Social',
    params: [],
  },
  {
    url: 'classquest.com',
    source: 'classquest',
    category: 'Social',
    params: [],
  },
  {
    url: 'cn.bing.com',
    source: 'cn.bing',
    category: 'Search',
    params: [],
  },
  {
    url: 'cnn.com',
    source: 'cnn',
    category: 'Search',
    params: [],
  },
  {
    url: 'co.pinterest.com',
    source: 'co.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'coccoc.com',
    source: 'C\u1ed1c C\u1ed1c',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'cocolog-nifty.com',
    source: 'cocolog-nifty',
    category: 'Social',
    params: [],
  },
  {
    url: 'copainsdavant.linternaute.com',
    source: 'copainsdavant.linternaute',
    category: 'Social',
    params: [],
  },
  {
    url: 'couchsurfing.org',
    source: 'couchsurfing',
    category: 'Social',
    params: [],
  },
  {
    url: 'cozycot.com',
    source: 'cozycot',
    category: 'Social',
    params: [],
  },
  {
    url: 'cr.shopping.naver.com',
    source: 'cr.shopping.naver',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'cr2.shopping.naver.com',
    source: 'cr2.shopping.naver',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'crackle.com',
    source: 'crackle',
    category: 'Video',
    params: [],
  },
  {
    url: 'cross.tv',
    source: 'cross',
    category: 'Social',
    params: [],
  },
  {
    url: 'crunchyroll.com',
    source: 'crunchyroll',
    category: 'Social',
    params: [],
  },
  {
    url: 'curiositystream.com',
    source: 'curiositystream',
    category: 'Video',
    params: [],
  },
  {
    url: 'cybre.space',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'cyworld.com',
    source: 'cyworld',
    category: 'Social',
    params: [],
  },
  {
    url: 'cz.pinterest.com',
    source: 'cz.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'd.hatena.ne.jp',
    source: 'd.hatena',
    category: 'Social',
    params: [],
  },
  {
    url: 'd.tube',
    source: 'd',
    category: 'Video',
    params: [],
  },
  {
    url: 'daemon-search.com',
    source: 'Daemon search',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'dailymotion.com',
    source: 'dailymotion',
    category: 'Video',
    params: [],
  },
  {
    url: 'dailystrength.org',
    source: 'dailystrength',
    category: 'Social',
    params: [],
  },
  {
    url: 'dashboard.twitch.tv',
    source: 'dashboard.twitch',
    category: 'Video',
    params: [],
  },
  {
    url: 'daum.com',
    source: 'daum',
    category: 'Search',
    params: [],
  },
  {
    url: 'daum.net',
    source: 'daum',
    category: 'Search',
    params: [],
  },
  {
    url: 'de.search.yahoo.com',
    source: 'de.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'deluxe.com',
    source: 'deluxe',
    category: 'Social',
    params: [],
  },
  {
    url: 'deviantart.com',
    source: 'deviantart',
    category: 'Social',
    params: [],
  },
  {
    url: 'dianping.com',
    source: 'dianping',
    category: 'Social',
    params: [],
  },
  {
    url: 'digg.com',
    source: 'digg',
    category: 'Social',
    params: [],
  },
  {
    url: 'diigo.com',
    source: 'diigo',
    category: 'Social',
    params: [],
  },
  {
    url: 'discover.hubpages.com',
    source: 'discover.hubpages',
    category: 'Social',
    params: [],
  },
  {
    url: 'disneyplus.com',
    source: 'disneyplus',
    category: 'Video',
    params: [],
  },
  {
    url: 'disqus.com',
    source: 'disqus',
    category: 'Social',
    params: [],
  },
  {
    url: 'dk.search.yahoo.com',
    source: 'dk.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'dogpile.com',
    source: 'InfoSpace',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'dogster.com',
    source: 'dogster',
    category: 'Social',
    params: [],
  },
  {
    url: 'dol2day.com',
    source: 'dol2day',
    category: 'Social',
    params: [],
  },
  {
    url: 'doostang.com',
    source: 'doostang',
    category: 'Social',
    params: [],
  },
  {
    url: 'dopplr.com',
    source: 'dopplr',
    category: 'Social',
    params: [],
  },
  {
    url: 'douban.com',
    source: 'Douban',
    category: 'Social',
    params: [],
  },
  {
    url: 'draft.blogger.com',
    source: 'draft.blogger',
    category: 'Social',
    params: [],
  },
  {
    url: 'draugiem.lv',
    source: 'draugiem',
    category: 'Social',
    params: [],
  },
  {
    url: 'dribbble.com',
    source: 'Dribbble',
    category: 'Social',
    params: [],
  },
  {
    url: 'drugs-forum.com',
    source: 'drugs-forum',
    category: 'Social',
    params: [],
  },
  {
    url: 'duckduckgo.com',
    source: 'duckduckgo',
    category: 'Search',
    params: [],
  },
  {
    url: 'dzone.com',
    source: 'dzone',
    category: 'Social',
    params: [],
  },
  {
    url: 'ebay.co.uk',
    source: 'ebay',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'ebay.com',
    source: 'ebay',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'ebay.com.au',
    source: 'ebay',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'ebay.de',
    source: 'ebay',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'ecosia.org',
    source: 'ecosia',
    category: 'Search',
    params: [],
  },
  {
    url: 'edublogs.org',
    source: 'edublogs',
    category: 'Social',
    params: [],
  },
  {
    url: 'elftown.com',
    source: 'elftown',
    category: 'Social',
    params: [],
  },
  {
    url: 'email.seznam.cz',
    source: 'email.seznam',
    category: 'Search',
    params: [],
  },
  {
    url: 'encrypted.google.com',
    source: 'Google',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'epicsearch.in',
    source: 'EpicSearch.in',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'epicurious.com',
    source: 'epicurious',
    category: 'Social',
    params: [],
  },
  {
    url: 'es.search.yahoo.com',
    source: 'es.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'espanol.images.yahoo.com',
    source: 'Yahoo! Images',
    category: 'Search',
    params: [
      'p',
      'va',
    ],
  },
  {
    url: 'espanol.search.yahoo.com',
    source: 'Yahoo!',
    category: 'Search',
    params: [
      'p',
      'q',
    ],
  },
  {
    url: 'etsy.com',
    source: 'etsy',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'eu.startpage.com',
    source: 'StartPage',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'everforo.com',
    source: 'everforo',
    category: 'Social',
    params: [],
  },
  {
    url: 'exalead.com',
    source: 'exalead',
    category: 'Search',
    params: [],
  },
  {
    url: 'exblog.jp',
    source: 'exblog',
    category: 'Social',
    params: [],
  },
  {
    url: 'excite.com',
    source: 'excite',
    category: 'Search',
    params: [],
  },
  {
    url: 'extole.com',
    source: 'extole',
    category: 'Social',
    params: [],
  },
  {
    url: 'facebook.com',
    source: 'Facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'faceparty.com',
    source: 'faceparty',
    category: 'Social',
    params: [],
  },
  {
    url: 'fandom.com',
    source: 'fandom',
    category: 'Social',
    params: [],
  },
  {
    url: 'fanpop.com',
    source: 'fanpop',
    category: 'Social',
    params: [],
  },
  {
    url: 'fark.com',
    source: 'fark',
    category: 'Social',
    params: [],
  },
  {
    url: 'fast.wistia.net',
    source: 'fast.wistia',
    category: 'Video',
    params: [],
  },
  {
    url: 'fb.com',
    source: 'fb',
    category: 'Social',
    params: [],
  },
  {
    url: 'fb.me',
    source: 'Facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'fc2.com',
    source: 'fc2',
    category: 'Social',
    params: [],
  },
  {
    url: 'feedspot.com',
    source: 'feedspot',
    category: 'Social',
    params: [],
  },
  {
    url: 'feministing.com',
    source: 'feministing',
    category: 'Social',
    params: [],
  },
  {
    url: 'fi.search.yahoo.com',
    source: 'fi.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'fi.zapmeta.com',
    source: 'Zapmeta',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'filmaffinity.com',
    source: 'filmaffinity',
    category: 'Social',
    params: [],
  },
  {
    url: 'firmy.cz',
    source: 'firmy',
    category: 'Search',
    params: [],
  },
  {
    url: 'flickr.com',
    source: 'flickr',
    category: 'Social',
    params: [],
  },
  {
    url: 'flipboard.com',
    source: 'flipboard',
    category: 'Social',
    params: [],
  },
  {
    url: 'flixster.com',
    source: 'Flixster',
    category: 'Social',
    params: [],
  },
  {
    url: 'folkdirect.com',
    source: 'folkdirect',
    category: 'Social',
    params: [],
  },
  {
    url: 'foodservice.com',
    source: 'foodservice',
    category: 'Social',
    params: [],
  },
  {
    url: 'foretag.118700.se',
    source: '118 700',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'forums.androidcentral.com',
    source: 'forums.androidcentral',
    category: 'Social',
    params: [],
  },
  {
    url: 'forums.crackberry.com',
    source: 'forums.crackberry',
    category: 'Social',
    params: [],
  },
  {
    url: 'forums.imore.com',
    source: 'forums.imore',
    category: 'Social',
    params: [],
  },
  {
    url: 'forums.nexopia.com',
    source: 'forums.nexopia',
    category: 'Social',
    params: [],
  },
  {
    url: 'forums.webosnation.com',
    source: 'forums.webosnation',
    category: 'Social',
    params: [],
  },
  {
    url: 'forums.wpcentral.com',
    source: 'forums.wpcentral',
    category: 'Social',
    params: [],
  },
  {
    url: 'fosstodon.org',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'fotki.com',
    source: 'fotki',
    category: 'Social',
    params: [],
  },
  {
    url: 'fotolog.com',
    source: 'Fotolog',
    category: 'Social',
    params: [],
  },
  {
    url: 'foursquare.com',
    source: 'Foursquare',
    category: 'Social',
    params: [],
  },
  {
    url: 'fr.search.yahoo.com',
    source: 'fr.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'fr2.rpmfind.net',
    source: 'rpmfind',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'free.facebook.com',
    source: 'free.facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'friendfeed.com',
    source: 'friendfeed',
    category: 'Social',
    params: [],
  },
  {
    url: 'friends.nico',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'friendsreunited.com',
    source: 'Friends Reunited',
    category: 'Social',
    params: [],
  },
  {
    url: 'friendster.com',
    source: 'Friendster',
    category: 'Social',
    params: [],
  },
  {
    url: 'fruehstueckstreff.org',
    source: 'fruehstueckstreff',
    category: 'Social',
    params: [],
  },
  {
    url: 'fubar.com',
    source: 'fubar',
    category: 'Social',
    params: [],
  },
  {
    url: 'gaiaonline.com',
    source: 'Gaia Online',
    category: 'Social',
    params: [],
  },
  {
    url: 'gamerdna.com',
    source: 'gamerdna',
    category: 'Social',
    params: [],
  },
  {
    url: 'gather.com',
    source: 'gather',
    category: 'Social',
    params: [],
  },
  {
    url: 'geni.com',
    source: 'geni',
    category: 'Social',
    params: [],
  },
  {
    url: 'getpocket.com',
    source: 'getpocket',
    category: 'Social',
    params: [],
  },
  {
    url: 'gibiru.com',
    source: 'Gibiru',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'github.com',
    source: 'GitHub',
    category: 'Social',
    params: [],
  },
  {
    url: 'glassboard.com',
    source: 'glassboard',
    category: 'Social',
    params: [],
  },
  {
    url: 'glassdoor.com',
    source: 'glassdoor',
    category: 'Social',
    params: [],
  },
  {
    url: 'global.bing.com',
    source: 'Bing',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'globo.com',
    source: 'globo',
    category: 'Search',
    params: [],
  },
  {
    url: 'go.mail.ru',
    source: 'go.mail',
    category: 'Search',
    params: [],
  },
  {
    url: 'godtube.com',
    source: 'godtube',
    category: 'Social',
    params: [],
  },
  {
    url: 'gogole.com',
    source: 'Google',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'goldenline.pl',
    source: 'goldenline',
    category: 'Social',
    params: [],
  },
  {
    url: 'goldstar.com',
    source: 'goldstar',
    category: 'Social',
    params: [],
  },
  {
    url: 'goo.gl',
    source: 'goo',
    category: 'Social',
    params: [],
  },
  {
    url: 'gooblog.com',
    source: 'gooblog',
    category: 'Social',
    params: [],
  },
  {
    url: 'goodreads.com',
    source: 'goodreads',
    category: 'Social',
    params: [],
  },
  {
    url: 'google.com',
    source: 'Google',
    category: 'Search',
    params: [],
  },
  {
    url: 'govloop.com',
    source: 'govloop',
    category: 'Social',
    params: [],
  },
  {
    url: 'gowalla.com',
    source: 'gowalla',
    category: 'Social',
    params: [],
  },
  {
    url: 'gree.jp',
    source: 'gree',
    category: 'Social',
    params: [],
  },
  {
    url: 'groups.google.com',
    source: 'groups.google',
    category: 'Social',
    params: [],
  },
  {
    url: 'gulli.com',
    source: 'gulli',
    category: 'Social',
    params: [],
  },
  {
    url: 'gutefrage.net',
    source: 'gutefrage',
    category: 'Social',
    params: [],
  },
  {
    url: 'habbo.com',
    source: 'Haboo',
    category: 'Social',
    params: [],
  },
  {
    url: 'hatena.com',
    source: 'Hatena',
    category: 'Social',
    params: [],
  },
  {
    url: 'help.hulu.com',
    source: 'help.hulu',
    category: 'Video',
    params: [],
  },
  {
    url: 'help.netflix.com',
    source: 'help.netflix',
    category: 'Video',
    params: [],
  },
  {
    url: 'hi5.com',
    source: 'hi5',
    category: 'Social',
    params: [],
  },
  {
    url: 'hk.search.yahoo.com',
    source: 'hk.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'hledani.tiscali.cz',
    source: 'Tiscali',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'holmes.ge',
    source: 'Holmes',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'hootsuite.com',
    source: 'hootsuite',
    category: 'Social',
    params: [],
  },
  {
    url: 'houzz.com',
    source: 'houzz',
    category: 'Social',
    params: [],
  },
  {
    url: 'hoverspot.com',
    source: 'hoverspot',
    category: 'Social',
    params: [],
  },
  {
    url: 'hr.com',
    source: 'hr',
    category: 'Social',
    params: [],
  },
  {
    url: 'hu.pinterest.com',
    source: 'hu.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'hubculture.com',
    source: 'hubculture',
    category: 'Social',
    params: [],
  },
  {
    url: 'hulu.com',
    source: 'hulu',
    category: 'Video',
    params: [],
  },
  {
    url: 'hyves.net',
    source: 'hyves',
    category: 'Social',
    params: [],
  },
  {
    url: 'hyves.nl',
    source: 'hyves',
    category: 'Social',
    params: [],
  },
  {
    url: 'ibibo.com',
    source: 'ibibo',
    category: 'Social',
    params: [],
  },
  {
    url: 'id.pinterest.com',
    source: 'id.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'id.search.yahoo.com',
    source: 'id.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'id.twitch.tv',
    source: 'id.twitch',
    category: 'Video',
    params: [],
  },
  {
    url: 'identi.ca',
    source: 'identi.ca',
    category: 'Social',
    params: [],
  },
  {
    url: 'ig.com',
    source: 'ig',
    category: 'Social',
    params: [],
  },
  {
    url: 'image.search.yahoo.co.jp',
    source: 'Yahoo! Japan Images',
    category: 'Search',
    params: [
      'p',
    ],
  },
  {
    url: 'images.search.yahoo.com',
    source: 'Yahoo! Images',
    category: 'Search',
    params: [
      'p',
      'va',
    ],
  },
  {
    url: 'images.yahoo.com',
    source: 'Yahoo! Images',
    category: 'Search',
    params: [
      'p',
      'va',
    ],
  },
  {
    url: 'images.yandex.com',
    source: 'Yandex Images',
    category: 'Search',
    params: [
      'text',
    ],
  },
  {
    url: 'images.yandex.ru',
    source: 'Yandex Images',
    category: 'Search',
    params: [
      'text',
    ],
  },
  {
    url: 'imageshack.com',
    source: 'imageshack',
    category: 'Social',
    params: [],
  },
  {
    url: 'imageshack.us',
    source: 'imageshack',
    category: 'Social',
    params: [],
  },
  {
    url: 'imvu.com',
    source: 'imvu',
    category: 'Social',
    params: [],
  },
  {
    url: 'in.pinterest.com',
    source: 'in.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'in.search.yahoo.com',
    source: 'in.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'incredimail.com',
    source: 'incredimail',
    category: 'Search',
    params: [],
  },
  {
    url: 'insanejournal.com',
    source: 'insanejournal',
    category: 'Social',
    params: [],
  },
  {
    url: 'instagram.com',
    source: 'instagram',
    category: 'Social',
    params: [],
  },
  {
    url: 'instapaper.com',
    source: 'instapaper',
    category: 'Social',
    params: [],
  },
  {
    url: 'int.search.tb.ask.com',
    source: 'Ask',
    category: 'Search',
    params: [
      'ask',
      'q',
      'searchfor',
    ],
  },
  {
    url: 'internations.org',
    source: 'internations',
    category: 'Social',
    params: [],
  },
  {
    url: 'interpals.net',
    source: 'interpals',
    category: 'Social',
    params: [],
  },
  {
    url: 'intherooms.com',
    source: 'intherooms',
    category: 'Social',
    params: [],
  },
  {
    url: 'iq.com',
    source: 'iq',
    category: 'Video',
    params: [],
  },
  {
    url: 'iqiyi.com',
    source: 'iqiyi',
    category: 'Video',
    params: [],
  },
  {
    url: 'irc-galleria.net',
    source: 'irc-galleria',
    category: 'Social',
    params: [],
  },
  {
    url: 'is.gd',
    source: 'is',
    category: 'Social',
    params: [],
  },
  {
    url: 'isearch.babylon.com',
    source: 'InfoSpace',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'isearch.glarysoft.com',
    source: 'InfoSpace',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'it.search.yahoo.com',
    source: 'it.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'italki.com',
    source: 'italki',
    category: 'Social',
    params: [],
  },
  {
    url: 'jammerdirect.com',
    source: 'jammerdirect',
    category: 'Social',
    params: [],
  },
  {
    url: 'jappy.com',
    source: 'jappy',
    category: 'Social',
    params: [],
  },
  {
    url: 'jappy.de',
    source: 'jappy',
    category: 'Social',
    params: [],
  },
  {
    url: 'jobs.netflix.com',
    source: 'jobs.netflix',
    category: 'Video',
    params: [],
  },
  {
    url: 'jp.hao123.com',
    source: 'Yahoo! Japan',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'justin.tv',
    source: 'justin',
    category: 'Video',
    params: [],
  },
  {
    url: 'jyxo.1188.cz',
    source: 'Jyxo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'k9safesearch.com',
    source: 'K9 Safe Search',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'kaboodle.com',
    source: 'kaboodle',
    category: 'Social',
    params: [],
  },
  {
    url: 'kakao.com',
    source: 'kakao',
    category: 'Social',
    params: [],
  },
  {
    url: 'kakaocorp.com',
    source: 'kakaocorp',
    category: 'Social',
    params: [],
  },
  {
    url: 'kaneva.com',
    source: 'kaneva',
    category: 'Social',
    params: [],
  },
  {
    url: 'kin.naver.com',
    source: 'kin.naver',
    category: 'Social',
    params: [],
  },
  {
    url: 'knzk.me',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'kvasir.com',
    source: 'kvasir',
    category: 'Search',
    params: [],
  },
  {
    url: 'kvasir.no',
    source: 'Kvasir',
    category: 'Search',
    params: [
      'q',
      'search_word',
    ],
  },
  {
    url: 'kwzf.net',
    source: '\ubb3b\uc9c0\ub9c8 \uac80\uc0c9',
    category: 'Search',
    params: [
      'search',
    ],
  },
  {
    url: 'l.facebook.com',
    source: 'Facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'l.instagram.com',
    source: 'Instagram',
    category: 'Social',
    params: [],
  },
  {
    url: 'l.messenger.com',
    source: 'l.messenger',
    category: 'Social',
    params: [],
  },
  {
    url: 'l.threads.net',
    source: 'Threads',
    category: 'Social',
    params: [],
  },
  {
    url: 'l.workplace.com',
    source: 'Workplace',
    category: 'Social',
    params: [],
  },
  {
    url: 'laban.vn',
    source: 'Laban',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'last.fm',
    source: 'last',
    category: 'Social',
    params: [],
  },
  {
    url: 'lastfm.com.br',
    source: 'Last.fm',
    category: 'Social',
    params: [],
  },
  {
    url: 'lastfm.com.tr',
    source: 'Last.fm',
    category: 'Social',
    params: [],
  },
  {
    url: 'lastfm.de',
    source: 'Last.fm',
    category: 'Social',
    params: [],
  },
  {
    url: 'lastfm.es',
    source: 'Last.fm',
    category: 'Social',
    params: [],
  },
  {
    url: 'lastfm.fr',
    source: 'Last.fm',
    category: 'Social',
    params: [],
  },
  {
    url: 'lastfm.it',
    source: 'Last.fm',
    category: 'Social',
    params: [],
  },
  {
    url: 'lastfm.jp',
    source: 'Last.fm',
    category: 'Social',
    params: [],
  },
  {
    url: 'lastfm.pl',
    source: 'Last.fm',
    category: 'Social',
    params: [],
  },
  {
    url: 'lastfm.ru',
    source: 'Last.fm',
    category: 'Social',
    params: [],
  },
  {
    url: 'lastfm.se',
    source: 'Last.fm',
    category: 'Social',
    params: [],
  },
  {
    url: 'lemoteur.orange.fr',
    source: 'Orange',
    category: 'Search',
    params: [
      'kw',
    ],
  },
  {
    url: 'lens.google.com',
    source: 'lens.google',
    category: 'Search',
    params: [],
  },
  {
    url: 'librarything.com',
    source: 'librarything',
    category: 'Social',
    params: [],
  },
  {
    url: 'lifestream.aol.com',
    source: 'lifestream.aol',
    category: 'Social',
    params: [],
  },
  {
    url: 'line.com',
    source: 'line',
    category: 'Social',
    params: [],
  },
  {
    url: 'line.me',
    source: 'line',
    category: 'Social',
    params: [],
  },
  {
    url: 'linkedin.com',
    source: 'linkedin',
    category: 'Social',
    params: [],
  },
  {
    url: 'listal.com',
    source: 'listal',
    category: 'Social',
    params: [],
  },
  {
    url: 'listings.altavista.com',
    source: 'AltaVista',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'listography.com',
    source: 'listography',
    category: 'Social',
    params: [],
  },
  {
    url: 'lite.qwant.com',
    source: 'lite.qwant',
    category: 'Search',
    params: [],
  },
  {
    url: 'livedoor.com',
    source: 'livedoor',
    category: 'Social',
    params: [],
  },
  {
    url: 'livejournal.com',
    source: 'livejournal',
    category: 'Social',
    params: [],
  },
  {
    url: 'livejournal.ru',
    source: 'LiveJournal',
    category: 'Social',
    params: [],
  },
  {
    url: 'lm.facebook.com',
    source: 'lm.facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'lm.workplace.com',
    source: 'Workplace',
    category: 'Social',
    params: [],
  },
  {
    url: 'lnkd.in',
    source: 'lnkd',
    category: 'Social',
    params: [],
  },
  {
    url: 'lo.st',
    source: 'Lo.st',
    category: 'Search',
    params: [
      'x_query',
    ],
  },
  {
    url: 'login.live.com',
    source: 'Windows Live Spaces',
    category: 'Social',
    params: [],
  },
  {
    url: 'login.tagged.com',
    source: 'Tagged',
    category: 'Social',
    params: [],
  },
  {
    url: 'lycos.com',
    source: 'lycos',
    category: 'Search',
    params: [],
  },
  {
    url: 'm.alibaba.com',
    source: 'm.alibaba',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'm.baidu.com',
    source: 'm.baidu',
    category: 'Search',
    params: [],
  },
  {
    url: 'm.blog.naver.com',
    source: 'm.blog.naver',
    category: 'Social',
    params: [],
  },
  {
    url: 'm.cafe.naver.com',
    source: 'm.cafe.naver',
    category: 'Social',
    params: [],
  },
  {
    url: 'm.facebook.com',
    source: 'Facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'm.kin.naver.com',
    source: 'm.kin.naver',
    category: 'Social',
    params: [],
  },
  {
    url: 'm.naver.com',
    source: 'm.naver',
    category: 'Search',
    params: [],
  },
  {
    url: 'm.search.naver.com',
    source: 'm.search.naver',
    category: 'Search',
    params: [],
  },
  {
    url: 'm.shopping.naver.com',
    source: 'm.shopping.naver',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'm.sm.cn',
    source: 'sm.cn',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'm.so.com',
    source: '360search',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'm.sogou.com',
    source: 'm.sogou',
    category: 'Search',
    params: [],
  },
  {
    url: 'm.sp.sm.cn',
    source: 'sm.cn',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'm.twitch.tv',
    source: 'm.twitch',
    category: 'Video',
    params: [],
  },
  {
    url: 'm.vk.com',
    source: 'm.vk',
    category: 'Social',
    params: [],
  },
  {
    url: 'm.yandex.com',
    source: 'Yandex',
    category: 'Search',
    params: [
      'text',
    ],
  },
  {
    url: 'm.yelp.com',
    source: 'm.yelp',
    category: 'Social',
    params: [],
  },
  {
    url: 'm.youtube.com',
    source: 'm.youtube',
    category: 'Video',
    params: [],
  },
  {
    url: 'mail.rambler.ru',
    source: 'mail.rambler',
    category: 'Search',
    params: [],
  },
  {
    url: 'mail.yandex.ru',
    source: 'mail.yandex',
    category: 'Search',
    params: [],
  },
  {
    url: 'malaysia.search.yahoo.com',
    source: 'Yahoo!',
    category: 'Search',
    params: [
      'p',
      'q',
    ],
  },
  {
    url: 'mamot.fr',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'mastodon.art',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'mastodon.at',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'mastodon.cloud',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'mastodon.social',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'mastodon.xyz',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'mastodont.cat',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'mbga.jp',
    source: 'mbga',
    category: 'Social',
    params: [],
  },
  {
    url: 'meetin.org',
    source: 'meetin',
    category: 'Social',
    params: [],
  },
  {
    url: 'meetup.com',
    source: 'meetup',
    category: 'Social',
    params: [],
  },
  {
    url: 'meinvz.net',
    source: 'meinvz',
    category: 'Social',
    params: [],
  },
  {
    url: 'meneame.net',
    source: 'meneame',
    category: 'Social',
    params: [],
  },
  {
    url: 'menuism.com',
    source: 'menuism',
    category: 'Social',
    params: [],
  },
  {
    url: 'mercadolibre.com',
    source: 'mercadolibre',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'mercadolibre.com.ar',
    source: 'mercadolibre',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'mercadolibre.com.mx',
    source: 'mercadolibre',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'message.alibaba.com',
    source: 'message.alibaba',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'messages.google.com',
    source: 'messages.google',
    category: 'Social',
    params: [],
  },
  {
    url: 'messages.yahoo.co.jp',
    source: 'messages.yahoo',
    category: 'Social',
    params: [],
  },
  {
    url: 'messenger.com',
    source: 'messenger',
    category: 'Social',
    params: [],
  },
  {
    url: 'metager.de',
    source: 'Metager',
    category: 'Search',
    params: [
      'eingabe',
    ],
  },
  {
    url: 'metager2.de',
    source: 'Metager2',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'mix.com',
    source: 'mix',
    category: 'Social',
    params: [],
  },
  {
    url: 'mixi.jp',
    source: 'mixi',
    category: 'Social',
    params: [],
  },
  {
    url: 'mobile.facebook.com',
    source: 'mobile.facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'mobile.virgilio.it',
    source: 'Virgilio',
    category: 'Search',
    params: [
      'qrs',
    ],
  },
  {
    url: 'mocospace.com',
    source: 'mocospace',
    category: 'Social',
    params: [],
  },
  {
    url: 'moikrug.ru',
    source: 'MoiKrug.ru',
    category: 'Social',
    params: [],
  },
  {
    url: 'mouthshut.com',
    source: 'mouthshut',
    category: 'Social',
    params: [],
  },
  {
    url: 'movabletype.com',
    source: 'movabletype',
    category: 'Social',
    params: [],
  },
  {
    url: 'msearch.shopping.naver.com',
    source: 'msearch.shopping.naver',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'msn.com',
    source: 'msn',
    category: 'Search',
    params: [],
  },
  {
    url: 'msnbc.msn.com',
    source: 'Bing',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'mstdn.io',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'mstdn.jp',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'mubi.com',
    source: 'mubi',
    category: 'Social',
    params: [],
  },
  {
    url: 'music.youtube.com',
    source: 'music.youtube',
    category: 'Video',
    params: [],
  },
  {
    url: 'my.daemon-search.com',
    source: 'Daemon search',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'my.mail.ru',
    source: 'my.mail.ru',
    category: 'Social',
    params: [],
  },
  {
    url: 'my.opera.com',
    source: 'my.opera',
    category: 'Social',
    params: [],
  },
  {
    url: 'myanimelist.net',
    source: 'myanimelist',
    category: 'Social',
    params: [],
  },
  {
    url: 'myheritage.com',
    source: 'myheritage',
    category: 'Social',
    params: [],
  },
  {
    url: 'mylife.com',
    source: 'mylife',
    category: 'Social',
    params: [],
  },
  {
    url: 'mylife.ru',
    source: 'MyLife',
    category: 'Social',
    params: [],
  },
  {
    url: 'mymodernmet.com',
    source: 'mymodernmet',
    category: 'Social',
    params: [],
  },
  {
    url: 'myspace.com',
    source: 'myspace',
    category: 'Social',
    params: [],
  },
  {
    url: 'naver.com',
    source: 'naver',
    category: 'Search',
    params: [],
  },
  {
    url: 'netflix.com',
    source: 'netflix',
    category: 'Video',
    params: [],
  },
  {
    url: 'netlog.com',
    source: 'Netlog',
    category: 'Social',
    params: [],
  },
  {
    url: 'netvibes.com',
    source: 'netvibes',
    category: 'Social',
    params: [],
  },
  {
    url: 'news.baidu.com',
    source: 'Baidu',
    category: 'Search',
    params: [
      'kw',
      'wd',
      'word',
    ],
  },
  {
    url: 'news.google.com',
    source: 'Google News',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'news.ycombinator.com',
    source: 'Hacker News',
    category: 'Social',
    params: [],
  },
  {
    url: 'nexopia.com',
    source: 'nexopia',
    category: 'Social',
    params: [],
  },
  {
    url: 'ngopost.org',
    source: 'ngopost',
    category: 'Social',
    params: [],
  },
  {
    url: 'nicovideo.jp',
    source: 'nicovideo',
    category: 'Social',
    params: [],
  },
  {
    url: 'nightlifelink.com',
    source: 'nightlifelink',
    category: 'Social',
    params: [],
  },
  {
    url: 'ning.com',
    source: 'ning',
    category: 'Social',
    params: [],
  },
  {
    url: 'nk.pl',
    source: 'Nasza-klasa.pl',
    category: 'Social',
    params: [],
  },
  {
    url: 'nl.pinterest.com',
    source: 'nl.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'nl.search.yahoo.com',
    source: 'nl.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'no.search.yahoo.com',
    source: 'no.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'no.shopping.net',
    source: 'no.shopping',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'no.zapmeta.com',
    source: 'Zapmeta',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'nortonsafe.search.ask.com',
    source: 'Ask',
    category: 'Search',
    params: [
      'ask',
      'q',
      'searchfor',
    ],
  },
  {
    url: 'nova.rambler.ru',
    source: 'Rambler',
    category: 'Search',
    params: [
      'query',
      'words',
    ],
  },
  {
    url: 'np.reddit.com',
    source: 'reddit',
    category: 'Social',
    params: [],
  },
  {
    url: 'ntp.msn.com',
    source: 'ntp.msn',
    category: 'Search',
    params: [],
  },
  {
    url: 'nz.search.yahoo.com',
    source: 'nz.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'odnoklassniki.ru',
    source: 'odnoklassniki',
    category: 'Social',
    params: [],
  },
  {
    url: 'odnoklassniki.ua',
    source: 'odnoklassniki',
    category: 'Social',
    params: [],
  },
  {
    url: 'offer.alibaba.com',
    source: 'offer.alibaba',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'okwave.jp',
    source: 'okwave',
    category: 'Social',
    params: [],
  },
  {
    url: 'old.reddit.com',
    source: 'old.reddit',
    category: 'Social',
    params: [],
  },
  {
    url: 'one.cn.yahoo.com',
    source: 'Yahoo!',
    category: 'Search',
    params: [
      'p',
      'q',
    ],
  },
  {
    url: 'one.walmart.com',
    source: 'one.walmart',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'onet.com',
    source: 'onet',
    category: 'Search',
    params: [],
  },
  {
    url: 'onet.pl',
    source: 'onet',
    category: 'Search',
    params: [],
  },
  {
    url: 'oneworldgroup.org',
    source: 'oneworldgroup',
    category: 'Social',
    params: [],
  },
  {
    url: 'online.no',
    source: 'Online.no',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'onstartups.com',
    source: 'onstartups',
    category: 'Social',
    params: [],
  },
  {
    url: 'opendiary.com',
    source: 'opendiary',
    category: 'Social',
    params: [],
  },
  {
    url: 'order.shopping.yahoo.co.jp',
    source: 'order.shopping.yahoo',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'orkut.com',
    source: 'Orkut',
    category: 'Social',
    params: [],
  },
  {
    url: 'oshiete.goo.ne.jp',
    source: 'oshiete.goo',
    category: 'Social',
    params: [],
  },
  {
    url: 'otsing.delfi.ee',
    source: 'Delfi EE',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'out.reddit.com',
    source: 'out.reddit',
    category: 'Social',
    params: [],
  },
  {
    url: 'over-blog.com',
    source: 'over-blog',
    category: 'Social',
    params: [],
  },
  {
    url: 'overblog.com',
    source: 'overblog',
    category: 'Social',
    params: [],
  },
  {
    url: 'paper.li',
    source: 'paper',
    category: 'Social',
    params: [],
  },
  {
    url: 'partners.shopify.com',
    source: 'partners.shopify',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'partyflock.nl',
    source: 'partyflock',
    category: 'Social',
    params: [],
  },
  {
    url: 'pawoo.net',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'pay.reddit.com',
    source: 'reddit',
    category: 'Social',
    params: [],
  },
  {
    url: 'pe.search.yahoo.com',
    source: 'pe.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'peepeth.com',
    source: 'Peepeth',
    category: 'Social',
    params: [],
  },
  {
    url: 'pesquisa.sapo.pt',
    source: 'Sapo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'ph.search.yahoo.com',
    source: 'ph.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'photobucket.com',
    source: 'photobucket',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinboard.com',
    source: 'pinboard',
    category: 'Social',
    params: [],
  },
  {
    url: 'pingsta.com',
    source: 'pingsta',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.at',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.ca',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.ch',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.cl',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.co.kr',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.co.uk',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.com',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.com.au',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.com.mx',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.de',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.dk',
    source: 'Pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.es',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.fr',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.ie',
    source: 'Pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.it',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.jp',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.nz',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.ph',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.pt',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.ru',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pinterest.se',
    source: 'pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pixiv.net',
    source: 'pixiv',
    category: 'Social',
    params: [],
  },
  {
    url: 'pl.pinterest.com',
    source: 'pl.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'pl.search.yahoo.com',
    source: 'pl.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'play.google.com',
    source: 'play.google',
    category: 'Search',
    params: [],
  },
  {
    url: 'playahead.se',
    source: 'playahead',
    category: 'Social',
    params: [],
  },
  {
    url: 'player.twitch.tv',
    source: 'player.twitch',
    category: 'Video',
    params: [],
  },
  {
    url: 'player.vimeo.com',
    source: 'player.vimeo',
    category: 'Video',
    params: [],
  },
  {
    url: 'plurk.com',
    source: 'plurk',
    category: 'Social',
    params: [],
  },
  {
    url: 'plus.google.com',
    source: 'plus.google',
    category: 'Social',
    params: [],
  },
  {
    url: 'pocket.co',
    source: 'pocket',
    category: 'Social',
    params: [],
  },
  {
    url: 'posterous.com',
    source: 'posterous',
    category: 'Social',
    params: [],
  },
  {
    url: 'pro.homeadvisor.com',
    source: 'pro.homeadvisor',
    category: 'Social',
    params: [],
  },
  {
    url: 'pulse.yahoo.com',
    source: 'pulse.yahoo',
    category: 'Social',
    params: [],
  },
  {
    url: 'qapacity.com',
    source: 'qapacity',
    category: 'Social',
    params: [],
  },
  {
    url: 'qc.images.yahoo.com',
    source: 'Yahoo! Images',
    category: 'Search',
    params: [
      'p',
      'va',
    ],
  },
  {
    url: 'qc.search.yahoo.com',
    source: 'Yahoo!',
    category: 'Search',
    params: [
      'p',
      'q',
    ],
  },
  {
    url: 'quark.sm.cn',
    source: 'sm.cn',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'quechup.com',
    source: 'quechup',
    category: 'Social',
    params: [],
  },
  {
    url: 'quey.org',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'quora.com',
    source: 'quora',
    category: 'Social',
    params: [],
  },
  {
    url: 'qwant.com',
    source: 'qwant',
    category: 'Search',
    params: [],
  },
  {
    url: 'qzone.qq.com',
    source: 'qzone.qq',
    category: 'Social',
    params: [],
  },
  {
    url: 'r.duckduckgo.com',
    source: 'DuckDuckGo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'rakuten.co.jp',
    source: 'rakuten',
    category: 'Search',
    params: [],
  },
  {
    url: 'rakuten.com',
    source: 'rakuten',
    category: 'Search',
    params: [],
  },
  {
    url: 'rambler.com',
    source: 'rambler',
    category: 'Search',
    params: [],
  },
  {
    url: 'rambler.ru',
    source: 'rambler',
    category: 'Search',
    params: [],
  },
  {
    url: 'ravelry.com',
    source: 'ravelry',
    category: 'Social',
    params: [],
  },
  {
    url: 'recherche.aol.fr',
    source: 'AOL',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'rechercher.aliceadsl.fr',
    source: 'Alice Adsl',
    category: 'Search',
    params: [
      'qs',
    ],
  },
  {
    url: 'reddit.com',
    source: 'reddit',
    category: 'Social',
    params: [],
  },
  {
    url: 'redux.com',
    source: 'redux',
    category: 'Social',
    params: [],
  },
  {
    url: 'renren.com',
    source: 'renren',
    category: 'Social',
    params: [],
  },
  {
    url: 'req.hit-parade.com',
    source: 'Hit-Parade',
    category: 'Search',
    params: [
      'p7',
    ],
  },
  {
    url: 'researchgate.net',
    source: 'researchgate',
    category: 'Social',
    params: [],
  },
  {
    url: 'results.searchlock.com',
    source: 'SearchLock',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'reunion.com',
    source: 'reunion',
    category: 'Social',
    params: [],
  },
  {
    url: 'reverbnation.com',
    source: 'reverbnation',
    category: 'Social',
    params: [],
  },
  {
    url: 'ro-mastodon.puyo.jp',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'rpmfind.net',
    source: 'rpmfind',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'rtl.de',
    source: 'rtl',
    category: 'Social',
    params: [],
  },
  {
    url: 'ryze.com',
    source: 'ryze',
    category: 'Social',
    params: [],
  },
  {
    url: 's1-eu5.startpage.com',
    source: 'StartPage',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 's12-eu5.startpage.com',
    source: 'StartPage',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 's2-eu4.startpage.com',
    source: 'StartPage',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 's3.amazonaws.com',
    source: 's3.amazonaws',
    category: 'Shopping',
    params: [],
  },
  {
    url: 's5-eu5.startpage.com',
    source: 'StartPage',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 's7-eu4.startpage.com',
    source: 'StartPage',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 's7-eu5.startpage.com',
    source: 'StartPage',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'safesearch.avira.com',
    source: 'Avira SafeSearch',
    category: 'Search',
    params: [
      'ask',
      'q',
      'searchfor',
    ],
  },
  {
    url: 'salespider.com',
    source: 'salespider',
    category: 'Social',
    params: [],
  },
  {
    url: 'scoop.it',
    source: 'scoop',
    category: 'Social',
    params: [],
  },
  {
    url: 'screenrant.com',
    source: 'screenrant',
    category: 'Social',
    params: [],
  },
  {
    url: 'scribd.com',
    source: 'scribd',
    category: 'Social',
    params: [],
  },
  {
    url: 'scvngr.com',
    source: 'scvngr',
    category: 'Social',
    params: [],
  },
  {
    url: 'se.search.yahoo.com',
    source: 'se.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'se.shopping.net',
    source: 'se.shopping',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'search-dyn.tiscali.it',
    source: 'Tiscali',
    category: 'Search',
    params: [
      'key',
      'q',
    ],
  },
  {
    url: 'search.aol.co.uk',
    source: 'AOL',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'search.aol.com',
    source: 'AOL',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'search.ask.com',
    source: 'Ask',
    category: 'Search',
    params: [
      'ask',
      'q',
      'searchfor',
    ],
  },
  {
    url: 'search.auone.jp',
    source: 'auone',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.avast.com',
    source: 'InfoSpace',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.b1.org',
    source: 'InfoSpace',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.babylon.com',
    source: 'Babylon',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.brave.com',
    source: 'Brave',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.centrum.cz',
    source: 'Centrum',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.comcast.net',
    source: 'Comcast',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.conduit.com',
    source: 'Conduit.com',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.daum.net',
    source: 'Daum',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.disconnect.me',
    source: 'DisconnectSearch',
    category: 'Search',
    params: [],
  },
  {
    url: 'search.free.fr',
    source: 'Free',
    category: 'Search',
    params: [
      'q',
      'qs',
    ],
  },
  {
    url: 'search.genieo.com',
    source: 'Genieo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.goo.ne.jp',
    source: 'goo',
    category: 'Search',
    params: [
      'mt',
    ],
  },
  {
    url: 'search.google.com',
    source: 'search.google',
    category: 'Search',
    params: [],
  },
  {
    url: 'search.handycafe.com',
    source: 'InfoSpace',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.iminent.com',
    source: 'InfoSpace',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.lilo.org',
    source: 'Lilo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.lookseek.com',
    source: 'Lookseek',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.lycos.com',
    source: 'Lycos',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'search.myway.com',
    source: 'MyWebSearch',
    category: 'Search',
    params: [
      'searchfor',
    ],
  },
  {
    url: 'search.mywebsearch.com',
    source: 'MyWebSearch',
    category: 'Search',
    params: [
      'searchfor',
    ],
  },
  {
    url: 'search.nate.com',
    source: 'Nate',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.naver.com',
    source: 'Naver',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'search.nifty.com',
    source: 'Nifty',
    category: 'Search',
    params: [
      'q',
      'text',
    ],
  },
  {
    url: 'search.seznam.cz',
    source: 'Seznam',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'search.smt.docomo.ne.jp',
    source: 'search.smt.docomo',
    category: 'Search',
    params: [],
  },
  {
    url: 'search.tb.ask.com',
    source: 'Ask',
    category: 'Search',
    params: [
      'ask',
      'q',
      'searchfor',
    ],
  },
  {
    url: 'search.tiscali.it',
    source: 'Tiscali',
    category: 'Search',
    params: [
      'key',
      'q',
    ],
  },
  {
    url: 'search.ukr.net',
    source: 'search.ukr',
    category: 'Search',
    params: [],
  },
  {
    url: 'search.www.ee',
    source: 'www v\u00e4rav',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'search.yahoo.co.jp',
    source: 'Yahoo! Japan',
    category: 'Search',
    params: [
      'p',
      'vp',
    ],
  },
  {
    url: 'search.yahoo.com',
    source: 'Yahoo!',
    category: 'Search',
    params: [
      'p',
      'q',
    ],
  },
  {
    url: 'search.yam.com',
    source: 'Yam',
    category: 'Search',
    params: [
      'k',
    ],
  },
  {
    url: 'search.yippy.com',
    source: 'Yippy',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'searchalot.com',
    source: 'Searchalot',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'searchatlas.centrum.cz',
    source: 'Atlas',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'searchlock.com',
    source: 'SearchLock',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'searchservice.myspace.com',
    source: 'MySpace',
    category: 'Search',
    params: [
      'qry',
    ],
  },
  {
    url: 'searchya.com',
    source: 'InfoSpace',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'secondlife.com',
    source: 'secondlife',
    category: 'Social',
    params: [],
  },
  {
    url: 'secureurl.ukr.net',
    source: 'secureurl.ukr',
    category: 'Search',
    params: [],
  },
  {
    url: 'serverfault.com',
    source: 'serverfault',
    category: 'Social',
    params: [],
  },
  {
    url: 'seznam.cz',
    source: 'seznam',
    category: 'Search',
    params: [],
  },
  {
    url: 'sharethis.com',
    source: 'sharethis',
    category: 'Social',
    params: [],
  },
  {
    url: 'shop.app',
    source: 'shop',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'shopify.com',
    source: 'shopify',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'shopping.naver.com',
    source: 'shopping.naver',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'shopping.yahoo.co.jp',
    source: 'shopping.yahoo',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'shopping.yahoo.com',
    source: 'shopping.yahoo',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'shopzilla.com',
    source: 'shopzilla',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'shvoong.com',
    source: 'shvoong',
    category: 'Social',
    params: [],
  },
  {
    url: 'simplycodes.com',
    source: 'simplycodes',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'sites.google.com',
    source: 'sites.google',
    category: 'Social',
    params: [],
  },
  {
    url: 'skyfeed.app',
    source: 'Bluesky',
    category: 'Social',
    params: [],
  },
  {
    url: 'skype.com',
    source: 'skype',
    category: 'Social',
    params: [],
  },
  {
    url: 'skyrock.com',
    source: 'skyrock',
    category: 'Social',
    params: [],
  },
  {
    url: 'slashdot.org',
    source: 'slashdot',
    category: 'Social',
    params: [],
  },
  {
    url: 'slideshare.net',
    source: 'slideshare',
    category: 'Social',
    params: [],
  },
  {
    url: 'smart.delfi.lv',
    source: 'Delfi lv',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'smartnews.com',
    source: 'smartnews',
    category: 'Social',
    params: [],
  },
  {
    url: 'snapchat.com',
    source: 'snapchat',
    category: 'Social',
    params: [],
  },
  {
    url: 'so.360.cn',
    source: '360search',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'so.com',
    source: 'so',
    category: 'Search',
    params: [],
  },
  {
    url: 'so.m.sm.cn',
    source: 'sm.cn',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'social.com',
    source: 'social',
    category: 'Social',
    params: [],
  },
  {
    url: 'social.tchncs.de',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'sociallife.com.br',
    source: 'sociallife',
    category: 'Social',
    params: [],
  },
  {
    url: 'socialvibe.com',
    source: 'socialvibe',
    category: 'Social',
    params: [],
  },
  {
    url: 'sogou.com',
    source: 'sogou',
    category: 'Search',
    params: [],
  },
  {
    url: 'sp-search.auone.jp',
    source: 'auone',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'sp-web.search.auone.jp',
    source: 'auone',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'spoke.com',
    source: 'spoke',
    category: 'Social',
    params: [],
  },
  {
    url: 'spruz.com',
    source: 'spruz',
    category: 'Social',
    params: [],
  },
  {
    url: 'ssense.com',
    source: 'ssense',
    category: 'Social',
    params: [],
  },
  {
    url: 'stackapps.com',
    source: 'stackapps',
    category: 'Social',
    params: [],
  },
  {
    url: 'stackexchange.com',
    source: 'stackexchange',
    category: 'Social',
    params: [],
  },
  {
    url: 'stackoverflow.com',
    source: 'stackoverflow',
    category: 'Social',
    params: [],
  },
  {
    url: 'stardoll.com',
    source: 'stardoll',
    category: 'Social',
    params: [],
  },
  {
    url: 'start.iplay.com',
    source: 'I-play',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'startpage.com',
    source: 'StartPage',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'startsiden.com',
    source: 'startsiden',
    category: 'Search',
    params: [],
  },
  {
    url: 'startsiden.no',
    source: 'Startsiden',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'stickam.com',
    source: 'stickam',
    category: 'Social',
    params: [],
  },
  {
    url: 'store.shopping.yahoo.co.jp',
    source: 'store.shopping.yahoo',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'stripe.com',
    source: 'stripe',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'studivz.net',
    source: 'studivz',
    category: 'Social',
    params: [],
  },
  {
    url: 'stumbleupon.com',
    source: 'StumbleUpon',
    category: 'Social',
    params: [],
  },
  {
    url: 'suche.aol.de',
    source: 'AOL',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'suche.freenet.de',
    source: 'Freenet',
    category: 'Search',
    params: [
      'keywords',
      'query',
    ],
  },
  {
    url: 'suche.t-online.de',
    source: 'T-Online',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'suche.web.de',
    source: 'Web.de',
    category: 'Search',
    params: [
      'q',
      'su',
    ],
  },
  {
    url: 'suomi24.fi',
    source: 'suomi24',
    category: 'Social',
    params: [],
  },
  {
    url: 'superuser.com',
    source: 'superuser',
    category: 'Social',
    params: [],
  },
  {
    url: 'surfcanyon.com',
    source: 'Surf Canyon',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'sweeva.com',
    source: 'sweeva',
    category: 'Social',
    params: [],
  },
  {
    url: 'szukaj.onet.pl',
    source: 'Onet.pl',
    category: 'Search',
    params: [
      'qt',
    ],
  },
  {
    url: 'szukaj.wp.pl',
    source: 'Wirtualna Polska',
    category: 'Search',
    params: [
      'szukaj',
    ],
  },
  {
    url: 't.cn',
    source: 'Weibo',
    category: 'Social',
    params: [],
  },
  {
    url: 't.co',
    source: 'Twitter',
    category: 'Social',
    params: [],
  },
  {
    url: 't.me',
    source: 't',
    category: 'Social',
    params: [],
  },
  {
    url: 'tagassistant.google.com',
    source: 'tagassistant.google.com',
    category: 'Referral',
    params: [],
  },
  {
    url: 'tagged.com',
    source: 'tagged',
    category: 'Social',
    params: [],
  },
  {
    url: 'taggedmail.com',
    source: 'taggedmail',
    category: 'Social',
    params: [],
  },
  {
    url: 'talkbiznow.com',
    source: 'talkbiznow',
    category: 'Social',
    params: [],
  },
  {
    url: 'taringa.net',
    source: 'taringa',
    category: 'Social',
    params: [],
  },
  {
    url: 'techmeme.com',
    source: 'techmeme',
    category: 'Social',
    params: [],
  },
  {
    url: 'technorati.com',
    source: 'Technorati',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'ted.com',
    source: 'ted',
    category: 'Video',
    params: [],
  },
  {
    url: 'tencent.com',
    source: 'tencent',
    category: 'Social',
    params: [],
  },
  {
    url: 'terra.com',
    source: 'terra',
    category: 'Search',
    params: [],
  },
  {
    url: 'th.search.yahoo.com',
    source: 'th.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'threads.net',
    source: 'Threads',
    category: 'Social',
    params: [],
  },
  {
    url: 'tieba.baidu.com',
    source: 'Baidu',
    category: 'Search',
    params: [
      'kw',
      'wd',
      'word',
    ],
  },
  {
    url: 'tiktok.com',
    source: 'TikTok',
    category: 'Social',
    params: [],
  },
  {
    url: 'tinyurl.com',
    source: 'tinyurl',
    category: 'Social',
    params: [],
  },
  {
    url: 'toolbox.com',
    source: 'toolbox',
    category: 'Social',
    params: [],
  },
  {
    url: 'touch.facebook.com',
    source: 'touch.facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'tr.pinterest.com',
    source: 'tr.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'tr.search.yahoo.com',
    source: 'tr.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'tr.zapmeta.com',
    source: 'Zapmeta',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'travellerspoint.com',
    source: 'travellerspoint',
    category: 'Social',
    params: [],
  },
  {
    url: 'tripadvisor.com',
    source: 'tripadvisor',
    category: 'Social',
    params: [],
  },
  {
    url: 'trombi.com',
    source: 'trombi',
    category: 'Social',
    params: [],
  },
  {
    url: 'trustpilot.com',
    source: 'trustpilot',
    category: 'Social',
    params: [],
  },
  {
    url: 'tudou.com',
    source: 'tudou',
    category: 'Social',
    params: [],
  },
  {
    url: 'tuenti.com',
    source: 'Tuenti',
    category: 'Social',
    params: [],
  },
  {
    url: 'tumblr.com',
    source: 'tumblr',
    category: 'Social',
    params: [],
  },
  {
    url: 'tut.by',
    source: 'tut',
    category: 'Search',
    params: [],
  },
  {
    url: 'tw.search.yahoo.com',
    source: 'tw.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'tweetdeck.com',
    source: 'tweetdeck',
    category: 'Social',
    params: [],
  },
  {
    url: 'twitch.com',
    source: 'twitch',
    category: 'Video',
    params: [],
  },
  {
    url: 'twitch.tv',
    source: 'twitch',
    category: 'Video',
    params: [],
  },
  {
    url: 'twitter.com',
    source: 'twitter',
    category: 'Social',
    params: [],
  },
  {
    url: 'twoo.com',
    source: 'twoo',
    category: 'Social',
    params: [],
  },
  {
    url: 'typepad.com',
    source: 'typepad',
    category: 'Social',
    params: [],
  },
  {
    url: 'uk.search.yahoo.com',
    source: 'uk.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'uk.shopping.net',
    source: 'uk.shopping',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'uk.zapmeta.com',
    source: 'Zapmeta',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'unblog.fr',
    source: 'unblog',
    category: 'Social',
    params: [],
  },
  {
    url: 'urbanspoon.com',
    source: 'urbanspoon',
    category: 'Social',
    params: [],
  },
  {
    url: 'us.search.yahoo.com',
    source: 'us.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'ushareit.com',
    source: 'ushareit',
    category: 'Social',
    params: [],
  },
  {
    url: 'ushi.cn',
    source: 'ushi',
    category: 'Social',
    params: [],
  },
  {
    url: 'utreon.com',
    source: 'utreon',
    category: 'Video',
    params: [],
  },
  {
    url: 'v2ex.com',
    source: 'V2EX',
    category: 'Social',
    params: [],
  },
  {
    url: 'vampirefreaks.com',
    source: 'vampirefreaks',
    category: 'Social',
    params: [],
  },
  {
    url: 'vampirerave.com',
    source: 'vampirerave',
    category: 'Social',
    params: [],
  },
  {
    url: 'veoh.com',
    source: 'veoh',
    category: 'Video',
    params: [],
  },
  {
    url: 'verden.abcsok.no',
    source: 'ABCs\u00f8k',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'viadeo.com',
    source: 'Viadeo',
    category: 'Social',
    params: [],
  },
  {
    url: 'viadeo.journaldunet.com',
    source: 'viadeo.journaldunet',
    category: 'Video',
    params: [],
  },
  {
    url: 'videa.seznam.cz',
    source: 'Seznam Videa',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'video.ibm.com',
    source: 'video.ibm',
    category: 'Social',
    params: [],
  },
  {
    url: 'video.search.yahoo.co.jp',
    source: 'Yahoo! Japan Videos',
    category: 'Search',
    params: [
      'p',
    ],
  },
  {
    url: 'vimeo.com',
    source: 'vimeo',
    category: 'Video',
    params: [],
  },
  {
    url: 'vis.social',
    source: 'Mastodon',
    category: 'Social',
    params: [],
  },
  {
    url: 'vk.com',
    source: 'Vkontakte',
    category: 'Social',
    params: [],
  },
  {
    url: 'vkontakte.ru',
    source: 'vkontakte',
    category: 'Social',
    params: [],
  },
  {
    url: 'vn.search.yahoo.com',
    source: 'vn.search.yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'wakoopa.com',
    source: 'wakoopa',
    category: 'Social',
    params: [],
  },
  {
    url: 'walmart.com',
    source: 'walmart',
    category: 'Shopping',
    params: [],
  },
  {
    url: 'wap.sogou.com',
    source: 'wap.sogou',
    category: 'Search',
    params: [],
  },
  {
    url: 'wattpad.com',
    source: 'wattpad',
    category: 'Social',
    params: [],
  },
  {
    url: 'web.ask.com',
    source: 'Ask',
    category: 'Search',
    params: [
      'ask',
      'q',
      'searchfor',
    ],
  },
  {
    url: 'web.canoe.ca',
    source: 'Canoe.ca',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'web.facebook.com',
    source: 'web.facebook',
    category: 'Social',
    params: [],
  },
  {
    url: 'web.skype.com',
    source: 'web.skype',
    category: 'Social',
    params: [],
  },
  {
    url: 'web.telegram.org',
    source: 'Telegram',
    category: 'Social',
    params: [],
  },
  {
    url: 'web.volny.cz',
    source: 'Volny',
    category: 'Search',
    params: [
      'search',
    ],
  },
  {
    url: 'webben.118700.se',
    source: '118 700',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'webmaster.yandex.ru',
    source: 'webmaster.yandex',
    category: 'Search',
    params: [],
  },
  {
    url: 'websearch.cs.com',
    source: 'Compuserve.com (Enhanced by Google)',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'websearch.rakuten.co.jp',
    source: 'websearch.rakuten',
    category: 'Search',
    params: [],
  },
  {
    url: 'webshots.com',
    source: 'webshots',
    category: 'Social',
    params: [],
  },
  {
    url: 'wechat.com',
    source: 'wechat',
    category: 'Social',
    params: [],
  },
  {
    url: 'weebly.com',
    source: 'weebly',
    category: 'Social',
    params: [],
  },
  {
    url: 'weeworld.com',
    source: 'WeeWorld',
    category: 'Social',
    params: [],
  },
  {
    url: 'weibo.com',
    source: 'Weibo',
    category: 'Social',
    params: [],
  },
  {
    url: 'wer-weiss-was.de',
    source: 'wer-weiss-was',
    category: 'Social',
    params: [],
  },
  {
    url: 'weread.com',
    source: 'weread',
    category: 'Social',
    params: [],
  },
  {
    url: 'whatsapp.com',
    source: 'whatsapp',
    category: 'Social',
    params: [],
  },
  {
    url: 'wiki.answers.com',
    source: 'wiki.answers',
    category: 'Social',
    params: [],
  },
  {
    url: 'wikihow.com',
    source: 'wikihow',
    category: 'Social',
    params: [],
  },
  {
    url: 'wikitravel.org',
    source: 'wikitravel',
    category: 'Social',
    params: [],
  },
  {
    url: 'wistia.com',
    source: 'wistia',
    category: 'Video',
    params: [],
  },
  {
    url: 'woot.com',
    source: 'woot',
    category: 'Social',
    params: [],
  },
  {
    url: 'wordpress.com',
    source: 'wordpress',
    category: 'Social',
    params: [],
  },
  {
    url: 'wordpress.org',
    source: 'wordpress',
    category: 'Social',
    params: [],
  },
  {
    url: 'workplace.com',
    source: 'Workplace',
    category: 'Social',
    params: [],
  },
  {
    url: 'www.118700.se',
    source: '118 700',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.1881.no',
    source: 'Opplysningen 1881',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.acoon.de',
    source: 'Acoon',
    category: 'Search',
    params: [
      'begriff',
    ],
  },
  {
    url: 'www.allaverksamheter.se',
    source: 'Allaverksamheter',
    category: 'Search',
    params: [
      'what',
    ],
  },
  {
    url: 'www.alltheinternet.com',
    source: 'AllTheInternet',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.alltheweb.com',
    source: 'AllTheWeb',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.altavista.com',
    source: 'AltaVista',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.arcor.de',
    source: 'Arcor',
    category: 'Search',
    params: [
      'keywords',
    ],
  },
  {
    url: 'www.ask.co.uk',
    source: 'Ask',
    category: 'Search',
    params: [
      'ask',
      'q',
      'searchfor',
    ],
  },
  {
    url: 'www.baidu.com',
    source: 'Baidu',
    category: 'Search',
    params: [
      'kw',
      'wd',
      'word',
    ],
  },
  {
    url: 'www.charter.net',
    source: 'Charter',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.dasoertliche.de',
    source: 'DasOertliche',
    category: 'Search',
    params: [
      'kw',
    ],
  },
  {
    url: 'www.entireweb.com',
    source: 'Entireweb',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.eurip.com',
    source: 'Eurip',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.euroseek.com',
    source: 'Euroseek',
    category: 'Search',
    params: [
      'string',
    ],
  },
  {
    url: 'www.everyclick.com',
    source: 'Everyclick',
    category: 'Search',
    params: [
      'keyword',
    ],
  },
  {
    url: 'www.exalead.com',
    source: 'Exalead',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.exalead.fr',
    source: 'Exalead',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.excite.co.jp',
    source: 'Excite',
    category: 'Search',
    params: [
      'search',
    ],
  },
  {
    url: 'www.facebook.com',
    source: 'Facebook',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.fixsuche.de',
    source: 'Fixsuche',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.gibiru.com',
    source: 'Gibiru',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.gnadenmeer.de',
    source: 'Gnadenmeer',
    category: 'Search',
    params: [
      'keyword',
    ],
  },
  {
    url: 'www.google.interia.pl',
    source: 'Interia',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.goyellow.de',
    source: 'GoYellow.de',
    category: 'Search',
    params: [
      'mdn',
    ],
  },
  {
    url: 'www.gulesider.no',
    source: 'Gule Sider',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.hit-parade.com',
    source: 'Hit-Parade',
    category: 'Search',
    params: [
      'p7',
    ],
  },
  {
    url: 'www.hooseek.com',
    source: 'Hooseek',
    category: 'Search',
    params: [
      'recherche',
    ],
  },
  {
    url: 'www.hotbot.com',
    source: 'Hotbot',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.icq.com',
    source: 'ICQ',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.ilse.nl',
    source: 'Ilse NL',
    category: 'Search',
    params: [
      'search_for',
    ],
  },
  {
    url: 'www.jungle-spider.de',
    source: 'Jungle Spider',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.kataweb.it',
    source: 'Kataweb',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.kvasir.no',
    source: 'Kvasir',
    category: 'Search',
    params: [
      'q',
      'search_word',
    ],
  },
  {
    url: 'www.lemoteur.fr',
    source: 'Voila',
    category: 'Search',
    params: [
      'rdata',
    ],
  },
  {
    url: 'www.looksmart.com',
    source: 'Looksmart',
    category: 'Search',
    params: [
      'key',
    ],
  },
  {
    url: 'www.maailm.com',
    source: 'maailm.com',
    category: 'Search',
    params: [
      'tekst',
    ],
  },
  {
    url: 'www.mamma.com',
    source: 'Mamma',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.metager.de',
    source: 'Metager',
    category: 'Search',
    params: [
      'eingabe',
    ],
  },
  {
    url: 'www.mister-wong.com',
    source: 'Mister Wong',
    category: 'Search',
    params: [
      'keywords',
    ],
  },
  {
    url: 'www.mister-wong.de',
    source: 'Mister Wong',
    category: 'Search',
    params: [
      'keywords',
    ],
  },
  {
    url: 'www.mojeek.com',
    source: 'Mojeek',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.mozbot.co.uk',
    source: 'mozbot',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.najdi.si',
    source: 'Najdi.si',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.neti.ee',
    source: 'Neti',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.only-search.com',
    source: 'OnlySearch',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.paperball.de',
    source: 'Paperball',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.picsearch.com',
    source: 'Picsearch',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.plazoo.com',
    source: 'Plazoo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.qualigo.at',
    source: 'Qualigo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.qualigo.ch',
    source: 'Qualigo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.qualigo.de',
    source: 'Qualigo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.qualigo.nl',
    source: 'Qualigo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.qwant.com',
    source: 'Qwant',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.riksdelen.se',
    source: 'Riksdelen',
    category: 'Search',
    params: [
      'what',
    ],
  },
  {
    url: 'www.search.ch',
    source: 'Search.ch',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.search.com',
    source: 'Search.com',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.searchcanvas.com',
    source: 'SearchCanvas',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.searchy.co.uk',
    source: 'Searchy',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.skynet.be',
    source: 'Skynet',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.so-net.ne.jp',
    source: 'So-net',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.so.com',
    source: '360search',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.sogou.com',
    source: 'Sogou',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.soso.com',
    source: 'Soso',
    category: 'Search',
    params: [
      'w',
    ],
  },
  {
    url: 'www.startpage.com',
    source: 'StartPage',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.startsiden.no',
    source: 'Startsiden',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.suchmaschine.com',
    source: 'Suchmaschine.com',
    category: 'Search',
    params: [
      'suchstr',
    ],
  },
  {
    url: 'www.talktalk.co.uk',
    source: 'TalkTalk',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.trouvez.com',
    source: 'Trouvez.com',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.url.org',
    source: 'URL.ORGanzier',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.vinden.nl',
    source: 'Vinden',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.walhello.info',
    source: 'Walhello',
    category: 'Search',
    params: [
      'key',
    ],
  },
  {
    url: 'www.web.nl',
    source: 'Web.nl',
    category: 'Search',
    params: [
      'zoekwoord',
    ],
  },
  {
    url: 'www.weborama.fr',
    source: 'weborama',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.witch.de',
    source: 'Witch',
    category: 'Search',
    params: [
      'search',
    ],
  },
  {
    url: 'www.woopie.jp',
    source: 'Woopie',
    category: 'Search',
    params: [
      'kw',
    ],
  },
  {
    url: 'www.x-recherche.com',
    source: 'X-Recherche',
    category: 'Search',
    params: [
      'mots',
    ],
  },
  {
    url: 'www.yandex.com',
    source: 'Yandex',
    category: 'Search',
    params: [
      'text',
    ],
  },
  {
    url: 'www.yasni.com',
    source: 'Yasni',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.yasni.de',
    source: 'Yasni',
    category: 'Search',
    params: [
      'query',
    ],
  },
  {
    url: 'www.yatedo.com',
    source: 'Yatedo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.zapmeta.com',
    source: 'Zapmeta',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'www.zoeken.nl',
    source: 'Zoeken',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www.zoznam.sk',
    source: 'Zoznam',
    category: 'Search',
    params: [
      's',
    ],
  },
  {
    url: 'www.zxuso.com',
    source: 'Zxuso',
    category: 'Search',
    params: [
      'wd',
    ],
  },
  {
    url: 'www1.baidu.com',
    source: 'Baidu',
    category: 'Search',
    params: [
      'kw',
      'wd',
      'word',
    ],
  },
  {
    url: 'www1.dastelefonbuch.de',
    source: 'DasTelefonbuch',
    category: 'Search',
    params: [
      'kw',
    ],
  },
  {
    url: 'www2.dasoertliche.de',
    source: 'DasOertliche',
    category: 'Search',
    params: [
      'kw',
      'ph',
    ],
  },
  {
    url: 'www2.inbox.com',
    source: 'Inbox',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'www3.zoek.nl',
    source: 'Zoek',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'wwwgoogle.com',
    source: 'Google',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'xanga.com',
    source: 'xanga',
    category: 'Social',
    params: [],
  },
  {
    url: 'xing.com',
    source: 'XING',
    category: 'Social',
    params: [],
  },
  {
    url: 'ya.ru',
    source: 'Yandex',
    category: 'Search',
    params: [
      'text',
    ],
  },
  {
    url: 'yahoo-mbga.jp',
    source: 'yahoo-mbga',
    category: 'Social',
    params: [],
  },
  {
    url: 'yahoo.co.jp',
    source: 'yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'yahoo.com',
    source: 'yahoo',
    category: 'Search',
    params: [],
  },
  {
    url: 'yammer.com',
    source: 'yammer',
    category: 'Social',
    params: [],
  },
  {
    url: 'yandex.by',
    source: 'yandex',
    category: 'Search',
    params: [],
  },
  {
    url: 'yandex.com',
    source: 'Yandex',
    category: 'Search',
    params: [
      'text',
    ],
  },
  {
    url: 'yandex.com.tr',
    source: 'yandex',
    category: 'Search',
    params: [],
  },
  {
    url: 'yandex.fr',
    source: 'yandex',
    category: 'Search',
    params: [],
  },
  {
    url: 'yandex.kz',
    source: 'yandex',
    category: 'Search',
    params: [],
  },
  {
    url: 'yandex.ru',
    source: 'Yandex',
    category: 'Search',
    params: [
      'text',
    ],
  },
  {
    url: 'yandex.ua',
    source: 'yandex',
    category: 'Search',
    params: [],
  },
  {
    url: 'yandex.uz',
    source: 'yandex',
    category: 'Search',
    params: [],
  },
  {
    url: 'yellowmap.de',
    source: 'Yellowmap',
    category: 'Search',
    params: [],
  },
  {
    url: 'yelp.com',
    source: 'yelp',
    category: 'Social',
    params: [],
  },
  {
    url: 'youku.com',
    source: 'youku',
    category: 'Video',
    params: [],
  },
  {
    url: 'youroom.in',
    source: 'youroom',
    category: 'Social',
    params: [],
  },
  {
    url: 'youtu.be',
    source: 'YouTube',
    category: 'Social',
    params: [],
  },
  {
    url: 'youtube.com',
    source: 'youtube',
    category: 'Video',
    params: [],
  },
  {
    url: 'yz.m.sm.cn',
    source: 'sm.cn',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'za.pinterest.com',
    source: 'za.pinterest',
    category: 'Social',
    params: [],
  },
  {
    url: 'zalo.com',
    source: 'zalo',
    category: 'Social',
    params: [],
  },
  {
    url: 'zapmeta.com',
    source: 'Zapmeta',
    category: 'Search',
    params: [
      'q',
      'query',
    ],
  },
  {
    url: 'zen.yandex.ru',
    source: 'zen.yandex',
    category: 'Search',
    params: [],
  },
  {
    url: 'zhidao.baidu.com',
    source: 'Baidu',
    category: 'Search',
    params: [
      'kw',
      'wd',
      'word',
    ],
  },
  {
    url: 'zoo.gr',
    source: 'zoo',
    category: 'Social',
    params: [],
  },
  {
    url: 'zoohoo.cz',
    source: 'Zoohoo',
    category: 'Search',
    params: [
      'q',
    ],
  },
  {
    url: 'zooppa.com',
    source: 'zooppa',
    category: 'Social',
    params: [],
  },
];