GET http://localhost:8080/api/app?pid=fdd1f346-c34e-41ee-971b-7f96484dad18&pageNumber=2
Accept: application/json

###

POST http://localhost:8080/api/app
Content-Type: application/json
X-Click-Stream-Request-Id: 605e367e-3fd8-4c59-8be5-e81869019999

{
  "projectId": "fdd1f346-c34e-41ee-971b-7f96484dad18",
  "name": "App-01",
  "description": "Description of App-01",
  "platform": "Web",
  "sdk": "Clickstream SDK"
}
###

GET http://localhost:8080/api/app/a7123164-6a63-4f3c-8236-f314acb26a5e?pid=fdd1f346-c34e-41ee-971b-7f96484dad18
Accept: application/json

###

PUT http://localhost:8080/api/app/a7123164-6a63-4f3c-8236-f314acb26a5e
Content-Type: application/json

{
  "appId": "a7123164-6a63-4f3c-8236-f314acb26a5e",
  "projectId": "fdd1f346-c34e-41ee-971b-7f96484dad18",
  "description": "Update Description of App-01"
}

###

DELETE http://localhost:8080/api/app/a7123164-6a63-4f3c-8236-f314acb26a5e?pid=fdd1f346-c34e-41ee-971b-7f96484dad18
Accept: application/json
