POST http://localhost:8080/api/pipeline
Content-Type: application/json
X-Click-Stream-Request-Id: 605e367e-3fd8-4c59-8be5-e81869017777

{
  "projectId": "571f8ab0-7b18-474c-9905-3cc4ddd5179f",
  "name": "Pipeline-01",
  "description": "Description of Pipeline-01",
  "base": {},
  "runtime": {},
  "ingestion": {},
  "etl": {},
  "dataModel": {}
}

###
GET http://localhost:8080/api/pipeline/75ba69d4-f011-434b-8757-e640d312da79?pid=571f8ab0-7b18-474c-9905-3cc4ddd5179f
Accept: application/json

###

PUT http://localhost:8080/api/pipeline/75ba69d4-f011-434b-8757-e640d312da79
Content-Type: application/json

{
  "projectId": "571f8ab0-7b18-474c-9905-3cc4ddd5179f",
  "version": "1676454801375",
  "ingestion": {},
  "updateAt": 1676454801375,
  "runtime": {},
  "pipelineId": "75ba69d4-f011-434b-8757-e640d312da79",
  "operator": "",
  "name": "111Pipeline-01",
  "base": {},
  "deleted": false,
  "createAt": 1676454801375,
  "description": "111Description of Pipeline-01",
  "etl": {},
  "dataModel": {},
  "type": "PIPELINE#75ba69d4-f011-434b-8757-e640d312da79#latest"
}

###

DELETE http://localhost:8080/api/pipeline/75ba69d4-f011-434b-8757-e640d312da79?pid=571f8ab0-7b18-474c-9905-3cc4ddd5179f
Accept: application/json
