/**
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
 *  with the License. A copy of the License is located at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
 *  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
 *  and limitations under the License.
 */

import { SelectProps } from '@cloudscape-design/components';
import {
  CategoryItemType,
  ERelationShip,
  IEventSegmentationItem,
  IEventSegmentationObj,
} from 'components/eventselect/AnalyticsType';
import {
  ConditionCategory,
  MetadataSource,
  MetadataValueType,
} from 'ts/explore-types';

export const EVENT_CATEGORIES: CategoryItemType[] = [
  {
    categoryName: '公共事件参数',
    categoryType: 'attribute',
    itemList: [
      {
        label: '事件时间戳',
        name: 'event_timestamp',
        value: 'new1203_mggt#app1#other#event_timestamp#int',
        description: '客户端上记录事件的时间（以微秒为单位，UTC）',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.OTHER,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '事件价值（USD）',
        name: 'event_value_in_usd',
        value: 'new1203_mggt#app1#other#event_value_in_usd#float',
        description: '事件的“值”参数的货币转换值（以USD为单位）',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.FLOAT,
        category: ConditionCategory.OTHER,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '平台',
        name: 'platform',
        value: 'new1203_mggt#app1#other#platform#string',
        description: '事件上报的平台',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.OTHER,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '项目ID',
        name: 'project_id',
        value: 'new1203_mggt#app1#other#project_id#string',
        description: '与应用相关联的项目ID',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.OTHER,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '用户ID',
        name: '_user_id',
        value: 'new1203_mggt#app1#event#_user_id#string',
        description: '通过 setUserId(）API分配给用户的唯一ID',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '用户匿名ID',
        name: '_user_pseudo_id',
        value: 'new1203_mggt#app1#event#_user_pseudo_id#string',
        description: 'SDK为匿名用户生成的伪ID',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备品牌名称',
        name: 'mobile_brand_name',
        value: 'new1203_mggt#app1#device#mobile_brand_name#string',
        description: '设备品牌名称',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备型号名称',
        name: 'mobile_model_name',
        value: 'new1203_mggt#app1#device#mobile_model_name#string',
        description: '设备型号名称',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备制造商名称',
        name: 'manufacturer',
        value: 'new1203_mggt#app1#device#manufacturer#string',
        description: '设备制造商名称',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备网络提供商名称',
        name: 'carrier',
        value: 'new1203_mggt#app1#device#carrier#string',
        description: '设备网络提供商名称',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备网络类型',
        name: 'network_type',
        value: 'new1203_mggt#app1#device#network_type#string',
        description: '设备的网络类型',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '操作系统',
        name: 'operating_system',
        value: 'new1203_mggt#app1#device#operating_system#string',
        description: '操作系统',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '操作系统版本',
        name: 'operating_system_version',
        value: 'new1203_mggt#app1#device#operating_system_version#string',
        description: '操作系统的版本',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '操作系统语言',
        name: 'system_language',
        value: 'new1203_mggt#app1#device#system_language#string',
        description: '操作系统的语言',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备ID',
        name: 'vendor_id',
        value: 'new1203_mggt#app1#device#vendor_id#string',
        description:
          '对于 iOS，这是 IDFV 或 UUID (仅当 IDFV 不可用)；对于安卓来说，这是 AndroidId 或 UUID (仅当 AndroidId 不可用)',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备广告ID',
        name: 'advertising_id',
        value: 'new1203_mggt#app1#device#advertising_id#string',
        description: '广告 ID/IDFA',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '时差',
        name: 'time_zone_offset_seconds',
        value: 'new1203_mggt#app1#device#time_zone_offset_seconds#int',
        description: '与 GMT 的偏移量（以秒为单位）',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA浏览器',
        name: 'ua_browser',
        value: 'new1203_mggt#app1#device#ua_browser#string',
        description: '用户查看内容的浏览器，从 User Agent 字符串中派生',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA浏览器版本',
        name: 'ua_browser_version',
        value: 'new1203_mggt#app1#device#ua_browser_version#string',
        description: '用户查看内容的浏览器版本，从 User Agent 字符串中派生',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA设备',
        name: 'ua_device',
        value: 'new1203_mggt#app1#device#ua_device#string',
        description: '用户查看内容的设备，从 User Agent 字符串中派生',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA设备类别',
        name: 'ua_device_category',
        value: 'new1203_mggt#app1#device#ua_device_category#string',
        description: '用户查看内容的设备类别，从 User Agent 字符串中派生',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA操作系统',
        name: 'ua_os',
        value: 'new1203_mggt#app1#device#ua_os#string',
        description: '用户查看内容的设备操作系统，从 User Agent 字符串中派生',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA操作系统版本',
        name: 'ua_os_version',
        value: 'new1203_mggt#app1#device#ua_os_version#string',
        description:
          '用户查看内容的设备操作系统版本，从 User Agent 字符串中派生',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '屏幕宽度',
        name: 'screen_width',
        value: 'new1203_mggt#app1#device#screen_width#int',
        description: '屏幕宽度',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '屏幕高度',
        name: 'screen_height',
        value: 'new1203_mggt#app1#device#screen_height#int',
        description: '屏幕高度',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '视区宽度',
        name: 'viewport_width',
        value: 'new1203_mggt#app1#device#viewport_width#int',
        description: '视区宽度',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '视区高度',
        name: 'viewport_height',
        value: 'new1203_mggt#app1#device#viewport_height#int',
        description: '视区高度',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '网站主机名',
        name: 'host_name',
        value: 'new1203_mggt#app1#device#host_name#string',
        description: '网站主机名',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.DEVICE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '大陆洲名',
        name: 'continent',
        value: 'new1203_mggt#app1#geo#continent#string',
        description: '基于 IP 地址报告事件的大陆洲名',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.GEO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '子大陆洲名',
        name: 'sub_continent',
        value: 'new1203_mggt#app1#geo#sub_continent#string',
        description: '基于 IP 地址报告事件的子大陆',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.GEO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '国家',
        name: 'country',
        value: 'new1203_mggt#app1#geo#country#string',
        description: '基于 IP 地址报告事件的国家',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.GEO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '地区',
        name: 'region',
        value: 'new1203_mggt#app1#geo#region#string',
        description: '基于 IP 地址报告事件的地区',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.GEO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '城市',
        name: 'city',
        value: 'new1203_mggt#app1#geo#city#string',
        description: '基于 IP 地址报告事件的城市',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.GEO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '纬度',
        name: 'latitude',
        value: 'new1203_mggt#app1#geo#latitude#double',
        description: '基于 IP 地址报告事件的纬度',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.DOUBLE,
        category: ConditionCategory.GEO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '经度',
        name: 'longitude',
        value: 'new1203_mggt#app1#geo#longitude#double',
        description: '基于 IP 地址报告事件的经度',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.DOUBLE,
        category: ConditionCategory.GEO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '地址推测精度',
        name: 'accuracy',
        value: 'new1203_mggt#app1#geo#accuracy#int',
        description: '基于 IP 地址报告事件的精度',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.GEO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '地理编号',
        name: 'locale',
        value: 'new1203_mggt#app1#geo#locale#string',
        description: '基于 IP 地址报告事件的地理编号',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.GEO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '流量活动名称',
        name: 'name',
        value: 'new1203_mggt#app1#traffic_source#name#string',
        description:
          '流量名称，存储事件记录时获取用户的营销活动，例如：夏季促销',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.TRAFFIC_SOURCE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '流量媒介',
        name: 'medium',
        value: 'new1203_mggt#app1#traffic_source#medium#string',
        description:
          '流量媒介，存储事件记录时获取用户的媒介，例如：电子邮件、付费搜索、搜索引擎',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.TRAFFIC_SOURCE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '流量来源',
        name: 'source',
        value: 'new1203_mggt#app1#traffic_source#source#string',
        description:
          '流量来源，事件报告时获取的网络来源的名称，例如：Google, Facebook, Bing, Baidu',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.TRAFFIC_SOURCE,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '软件包名',
        name: 'id',
        value: 'new1203_mggt#app1#app_info#id#string',
        description: '应用程序的软件包名称或 Bundle ID',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.APP_INFO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'App ID',
        name: 'app_id',
        value: 'new1203_mggt#app1#app_info#app_id#string',
        description: '与应用相关联的 App ID',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.APP_INFO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '应用程序安装商店',
        name: 'install_source',
        value: 'new1203_mggt#app1#app_info#install_source#string',
        description: '安装应用程序的商店',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.APP_INFO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '应用程序版本',
        name: 'version',
        value: 'new1203_mggt#app1#app_info#version#string',
        description: '应用程序的版本号',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.APP_INFO,
        platform: [],
        values: [],
        modifyTime: '-',
      },
    ],
  },
  {
    categoryName: '私有事件参数',
    categoryType: 'attribute',
    itemList: [
      {
        label: '屏幕ID',
        name: '_screen_id',
        value: 'new1203_mggt#app1#event#_screen_id#string',
        description: '屏幕ID',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '上一个屏幕名称',
        name: '_previous_screen_name',
        value: 'new1203_mggt#app1#event#_previous_screen_name#string',
        description: '上一个屏幕名称',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '上一个屏幕名称',
        name: '_previous_screen_id',
        value: 'new1203_mggt#app1#event#_previous_screen_id#string',
        description: '上一个屏幕ID',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '上一个屏幕的唯一ID',
        name: '_previous_screen_unique_id',
        value: 'new1203_mggt#app1#event#_previous_screen_unique_id#string',
        description: '上一个屏幕唯一ID',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '前序页面',
        name: '_page_referrer',
        value: 'new1203_mggt#app1#event#_page_referrer#string',
        description: '前一个页面URL',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '前序页面标题',
        name: '_page_referrer_title',
        value: 'new1203_mggt#app1#event#_page_referrer_title#string',
        description: '前一个页面标题',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '是否为会话进入页面',
        name: '_entrances',
        value: 'new1203_mggt#app1#event#_entrances#int',
        description: '会话中的第一个屏幕浏览事件该值为 1，其他则为 0',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '上一个界面浏览时间',
        name: '_previous_timestamp',
        value: 'new1203_mggt#app1#event#_previous_timestamp#int',
        description: '上一个界面浏览事件的时间戳',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '上个界面曝光时长(毫秒）',
        name: '_engagement_time_msec',
        value: 'new1203_mggt#app1#event#_engagement_time_msec#int',
        description: '上个屏幕最近一次在前台的时长的毫秒数',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '是否首次应用启动',
        name: '_is_first_time',
        value: 'new1203_mggt#app1#event#_is_first_time#string',
        description: '当应用程序启动后第一个 _app_start 事件时，值为 true',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '异常消息',
        name: '_exception_message',
        value: 'new1203_mggt#app1#event#_exception_message#string',
        description: '异常事件发出的消息',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '异常事件捕获的详细堆栈信息',
        name: '_exception_stack',
        value: 'new1203_mggt#app1#event#_exception_stack#string',
        description: '异常堆栈信息',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '上个应用版本',
        name: '_previous_app_version',
        value: 'new1203_mggt#app1#event#_previous_app_version#string',
        description: '上一个应用版本',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '上个操作系统版本',
        name: '_previous_os_version',
        value: 'new1203_mggt#app1#event#_previous_os_version#string',
        description: '上一个操作系统版本',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '数据错误代码',
        name: '_error_code',
        value: 'new1203_mggt#app1#event#_error_code#string',
        description: '上报数据时出现错误的代码',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '上报数据时出现错误的代码',
        name: '_error_message',
        value: 'new1203_mggt#app1#event#_error_message#string',
        description: '错误信息',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '搜索关键词',
        name: '_search_key',
        value: 'new1203_mggt#app1#event#_search_key#string',
        description: '搜索关键词',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '搜索内容',
        name: '_search_term',
        value: 'new1203_mggt#app1#event#_search_term#string',
        description: '搜索内容',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '外链类',
        name: '_link_classes',
        value: 'new1203_mggt#app1#event#_link_classes#string',
        description: '标签<a>中class里的内容',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '外链的类',
        name: '_link_domain',
        value: 'new1203_mggt#app1#event#_link_domain#string',
        description: '标签 <a>中href里的域名',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '外链ID',
        name: '_link_id',
        value: 'new1203_mggt#app1#event#_link_id#string',
        description: '标签 <a>中id里的内容',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '外链地址',
        name: '_link_url',
        value: 'new1203_mggt#app1#event#_link_url#string',
        description: '标签 <a>中href里的内容',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '是否外链',
        name: '_outbound',
        value: 'new1203_mggt#app1#event#_outbound#string',
        description: '如果该域不在配置的域名列表中，则属性值为true',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '流量媒介',
        name: '_traffic_source_medium',
        value: 'new1203_mggt#app1#event#_traffic_source_medium#string',
        description:
          '流量媒介，存储事件记录时获取用户的媒介，例如：电子邮件、付费搜索、搜索引擎',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '流量名称',
        name: '_traffic_source_name',
        value: 'new1203_mggt#app1#event#_traffic_source_name#string',
        description:
          '流量名称，存储事件记录时获取用户的营销活动，例如：夏季促销',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '流量来源',
        name: '_traffic_source_source',
        value: 'new1203_mggt#app1#event#_traffic_source_source#string',
        description:
          '流量来源，事件报告时获取的网络来源的名称，例如：Google, Facebook, Bing, Baidu',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '会话ID',
        name: '_session_id',
        value: 'new1203_mggt#app1#event#_session_id#string',
        description: '会话ID',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '会话开始时间戳',
        name: '_session_start_timestamp',
        value: 'new1203_mggt#app1#event#_session_start_timestamp#int',
        description: '会话开始时间戳',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '会话时长(毫秒）',
        name: '_session_duration',
        value: 'new1203_mggt#app1#event#_session_duration#int',
        description: '会话持续时间,毫秒为单位',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '会话编号',
        name: '_session_number',
        value: 'new1203_mggt#app1#event#_session_number#int',
        description: '当前用户的会话编号',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.INTEGER,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '最近一次站外链接',
        name: '_latest_referrer',
        value: 'new1203_mggt#app1#event#_latest_referrer#string',
        description: '最近一次站外链接',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '最近一次站外链接域名',
        name: '_latest_referrer_host',
        value: 'new1203_mggt#app1#event#_latest_referrer_host#string',
        description: '最近一次站外域名',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '屏幕名称',
        name: '_screen_name',
        value: 'new1203_mggt#app1#event#_screen_name#string',
        description: '屏幕名称',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '屏幕唯一ID',
        name: '_screen_unique_id',
        value: 'new1203_mggt#app1#event#_screen_unique_id#string',
        description: 'App渲染屏幕时生成唯一ID',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '页面标题',
        name: '_page_title',
        value: 'new1203_mggt#app1#event#_page_title#string',
        description: '页面标题',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '页面URL',
        name: '_page_url',
        value: 'new1203_mggt#app1#event#_page_url#string',
        description: '页面URL',
        metadataSource: MetadataSource.PRESET,
        valueType: MetadataValueType.STRING,
        category: ConditionCategory.EVENT,
        platform: [],
        values: [],
        modifyTime: '-',
      },
    ],
  },
  //   {
  //     categoryName: '用户属性',
  //     categoryType: 'attribute',
  //     itemList: [
  //       {
  //         label: '用户ID',
  //         name: '_user_id',
  //         value: 'new1203_mggt#app1#user#_user_id#string',
  //         description:
  //           '通过 setUserId(）API分配给用户的唯一ID,通常是您业务系统的用户ID',
  //         metadataSource: MetadataSource.PRESET,
  //         valueType: MetadataValueType.STRING,
  //         category: 'user',
  //         values: [],
  //         modifyTime: '2024-03-05 09:25:40',
  //       },
  //       {
  //         label: '首次访问时间戳',
  //         name: '_user_first_touch_timestamp',
  //         value: 'new1203_mggt#app1#user#_user_first_touch_timestamp#int',
  //         description:
  //           '用户首次打开应用程序或访问站点的时间（以毫秒为单位），每个事件的 user 对象的都包含此属性',
  //         metadataSource: MetadataSource.PRESET,
  //         valueType: MetadataValueType.INTEGER,
  //         category: 'user',
  //         values: [],
  //         modifyTime: '2024-03-05 09:25:40',
  //       },
  //       {
  //         label: '首次访问日期',
  //         name: '_first_visit_date',
  //         value: 'new1203_mggt#app1#user_outer#_first_visit_date#string',
  //         description: '用户首次打开应用程序或访问站点的日期',
  //         metadataSource: MetadataSource.PRESET,
  //         valueType: MetadataValueType.STRING,
  //         category: 'user_outer',
  //         values: [],
  //         modifyTime: '2024-03-05 09:25:40',
  //       },
  //       {
  //         label: '首次访问前序外链地址',
  //         name: '_first_referer',
  //         value: 'new1203_mggt#app1#user_outer#_first_referer#string',
  //         description: '用户第一次打开应用程序时的外链',
  //         metadataSource: MetadataSource.PRESET,
  //         valueType: MetadataValueType.STRING,
  //         category: 'user_outer',
  //         values: [],
  //         modifyTime: '2024-03-05 09:25:40',
  //       },
  //       {
  //         label: '首次访问流量来源类型',
  //         name: '_first_traffic_source_type',
  //         value: 'new1203_mggt#app1#user_outer#_first_traffic_source_type#string',
  //         description: '第一个捕获的流量源',
  //         metadataSource: MetadataSource.PRESET,
  //         valueType: MetadataValueType.STRING,
  //         category: 'user_outer',
  //         values: [],
  //         modifyTime: '2024-03-05 09:25:40',
  //       },
  //       {
  //         label: '首次访问流量媒介',
  //         name: '_first_traffic_medium',
  //         value: 'new1203_mggt#app1#user_outer#_first_traffic_medium#string',
  //         description: '第一个捕获的流量媒介',
  //         metadataSource: MetadataSource.PRESET,
  //         valueType: MetadataValueType.STRING,
  //         category: 'user_outer',
  //         values: [],
  //         modifyTime: '2024-03-05 09:25:40',
  //       },
  //       {
  //         label: '首次访问流量来源名称',
  //         name: '_first_traffic_source',
  //         value: 'new1203_mggt#app1#user_outer#_first_traffic_source#string',
  //         description: '第一个捕获的流量来源',
  //         metadataSource: MetadataSource.PRESET,
  //         valueType: MetadataValueType.STRING,
  //         category: 'user_outer',
  //         values: [],
  //         modifyTime: '2024-03-05 09:25:40',
  //       },
  //       {
  //         label: '首次访问安装来源',
  //         name: '_channel',
  //         value: 'new1203_mggt#app1#user_outer#_channel#string',
  //         description: '第一个捕获的渠道',
  //         metadataSource: MetadataSource.PRESET,
  //         valueType: MetadataValueType.STRING,
  //         category: 'user_outer',
  //         values: [],
  //         modifyTime: '2024-03-05 09:25:40',
  //       },
  //     ],
  //   },
];

export const PRESET_PARAMETERS: any = [
  {
    categoryName: '公共事件参数',
    categoryType: 'attribute',
    itemList: [
      {
        label: '事件时间戳',
        name: 'event_timestamp',
        value: 'new1203_mggt#app1#other#event_timestamp#int',
        description: '客户端上记录事件的时间（以微秒为单位，UTC）',
        metadataSource: 'Preset',
        valueType: 'int',
        category: 'other',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '事件价值（USD）',
        name: 'event_value_in_usd',
        value: 'new1203_mggt#app1#other#event_value_in_usd#float',
        description: '事件的“值”参数的货币转换值（以USD为单位）',
        metadataSource: 'Preset',
        valueType: 'float',
        category: 'other',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '平台',
        name: 'platform',
        value: 'new1203_mggt#app1#other#platform#string',
        description: '事件上报的平台',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'other',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '项目ID',
        name: 'project_id',
        value: 'new1203_mggt#app1#other#project_id#string',
        description: '与应用相关联的项目ID',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'other',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '用户ID',
        name: '_user_id',
        value: 'new1203_mggt#app1#event#_user_id#string',
        description: '通过 setUserId(）API分配给用户的唯一ID',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'event',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '用户匿名ID',
        name: '_user_pseudo_id',
        value: 'new1203_mggt#app1#event#_user_pseudo_id#string',
        description: 'SDK为匿名用户生成的伪ID',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'event',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备品牌名称',
        name: 'mobile_brand_name',
        value: 'new1203_mggt#app1#device#mobile_brand_name#string',
        description: '设备品牌名称',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备型号名称',
        name: 'mobile_model_name',
        value: 'new1203_mggt#app1#device#mobile_model_name#string',
        description: '设备型号名称',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备制造商名称',
        name: 'manufacturer',
        value: 'new1203_mggt#app1#device#manufacturer#string',
        description: '设备制造商名称',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备网络提供商名称',
        name: 'carrier',
        value: 'new1203_mggt#app1#device#carrier#string',
        description: '设备网络提供商名称',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备网络类型',
        name: 'network_type',
        value: 'new1203_mggt#app1#device#network_type#string',
        description: '设备的网络类型',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '操作系统',
        name: 'operating_system',
        value: 'new1203_mggt#app1#device#operating_system#string',
        description: '操作系统',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '操作系统版本',
        name: 'operating_system_version',
        value: 'new1203_mggt#app1#device#operating_system_version#string',
        description: '操作系统的版本',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '操作系统语言',
        name: 'system_language',
        value: 'new1203_mggt#app1#device#system_language#string',
        description: '操作系统的语言',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备ID',
        name: 'vendor_id',
        value: 'new1203_mggt#app1#device#vendor_id#string',
        description:
          '对于 iOS，这是 IDFV 或 UUID (仅当 IDFV 不可用)；对于安卓来说，这是 AndroidId 或 UUID (仅当 AndroidId 不可用)',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '设备广告ID',
        name: 'advertising_id',
        value: 'new1203_mggt#app1#device#advertising_id#string',
        description: '广告 ID/IDFA',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '时差',
        name: 'time_zone_offset_seconds',
        value: 'new1203_mggt#app1#device#time_zone_offset_seconds#int',
        description: '与 GMT 的偏移量（以秒为单位）',
        metadataSource: 'Preset',
        valueType: 'int',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA浏览器',
        name: 'ua_browser',
        value: 'new1203_mggt#app1#device#ua_browser#string',
        description: '用户查看内容的浏览器，从 User Agent 字符串中派生',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA浏览器版本',
        name: 'ua_browser_version',
        value: 'new1203_mggt#app1#device#ua_browser_version#string',
        description: '用户查看内容的浏览器版本，从 User Agent 字符串中派生',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA设备',
        name: 'ua_device',
        value: 'new1203_mggt#app1#device#ua_device#string',
        description: '用户查看内容的设备，从 User Agent 字符串中派生',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA设备类别',
        name: 'ua_device_category',
        value: 'new1203_mggt#app1#device#ua_device_category#string',
        description: '用户查看内容的设备类别，从 User Agent 字符串中派生',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA操作系统',
        name: 'ua_os',
        value: 'new1203_mggt#app1#device#ua_os#string',
        description: '用户查看内容的设备操作系统，从 User Agent 字符串中派生',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'UA操作系统版本',
        name: 'ua_os_version',
        value: 'new1203_mggt#app1#device#ua_os_version#string',
        description:
          '用户查看内容的设备操作系统版本，从 User Agent 字符串中派生',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '屏幕宽度',
        name: 'screen_width',
        value: 'new1203_mggt#app1#device#screen_width#int',
        description: '屏幕宽度',
        metadataSource: 'Preset',
        valueType: 'int',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '屏幕高度',
        name: 'screen_height',
        value: 'new1203_mggt#app1#device#screen_height#int',
        description: '屏幕高度',
        metadataSource: 'Preset',
        valueType: 'int',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '视区宽度',
        name: 'viewport_width',
        value: 'new1203_mggt#app1#device#viewport_width#int',
        description: '视区宽度',
        metadataSource: 'Preset',
        valueType: 'int',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '视区高度',
        name: 'viewport_height',
        value: 'new1203_mggt#app1#device#viewport_height#int',
        description: '视区高度',
        metadataSource: 'Preset',
        valueType: 'int',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '网站主机名',
        name: 'host_name',
        value: 'new1203_mggt#app1#device#host_name#string',
        description: '网站主机名',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'device',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '大陆洲名',
        name: 'continent',
        value: 'new1203_mggt#app1#geo#continent#string',
        description: '基于 IP 地址报告事件的大陆洲名',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'geo',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '子大陆洲名',
        name: 'sub_continent',
        value: 'new1203_mggt#app1#geo#sub_continent#string',
        description: '基于 IP 地址报告事件的子大陆',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'geo',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '国家',
        name: 'country',
        value: 'new1203_mggt#app1#geo#country#string',
        description: '基于 IP 地址报告事件的国家',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'geo',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '地区',
        name: 'region',
        value: 'new1203_mggt#app1#geo#region#string',
        description: '基于 IP 地址报告事件的地区',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'geo',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '城市',
        name: 'city',
        value: 'new1203_mggt#app1#geo#city#string',
        description: '基于 IP 地址报告事件的城市',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'geo',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '纬度',
        name: 'latitude',
        value: 'new1203_mggt#app1#geo#latitude#double',
        description: '基于 IP 地址报告事件的纬度',
        metadataSource: 'Preset',
        valueType: 'double',
        category: 'geo',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '经度',
        name: 'longitude',
        value: 'new1203_mggt#app1#geo#longitude#double',
        description: '基于 IP 地址报告事件的经度',
        metadataSource: 'Preset',
        valueType: 'double',
        category: 'geo',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '地址推测精度',
        name: 'accuracy',
        value: 'new1203_mggt#app1#geo#accuracy#int',
        description: '基于 IP 地址报告事件的精度',
        metadataSource: 'Preset',
        valueType: 'int',
        category: 'geo',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '地理编号',
        name: 'locale',
        value: 'new1203_mggt#app1#geo#locale#string',
        description: '基于 IP 地址报告事件的地理编号',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'geo',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '流量活动名称',
        name: 'name',
        value: 'new1203_mggt#app1#traffic_source#name#string',
        description:
          '流量名称，存储事件记录时获取用户的营销活动，例如：夏季促销',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'traffic_source',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '流量媒介',
        name: 'medium',
        value: 'new1203_mggt#app1#traffic_source#medium#string',
        description:
          '流量媒介，存储事件记录时获取用户的媒介，例如：电子邮件、付费搜索、搜索引擎',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'traffic_source',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '流量来源',
        name: 'source',
        value: 'new1203_mggt#app1#traffic_source#source#string',
        description:
          '流量来源，事件报告时获取的网络来源的名称，例如：Google, Facebook, Bing, Baidu',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'traffic_source',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '软件包名',
        name: 'id',
        value: 'new1203_mggt#app1#app_info#id#string',
        description: '应用程序的软件包名称或 Bundle ID',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'app_info',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: 'App ID',
        name: 'app_id',
        value: 'new1203_mggt#app1#app_info#app_id#string',
        description: '与应用相关联的 App ID',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'app_info',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '应用程序安装商店',
        name: 'install_source',
        value: 'new1203_mggt#app1#app_info#install_source#string',
        description: '安装应用程序的商店',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'app_info',
        platform: [],
        values: [],
        modifyTime: '-',
      },
      {
        label: '应用程序版本',
        name: 'version',
        value: 'new1203_mggt#app1#app_info#version#string',
        description: '应用程序的版本号',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'app_info',
        platform: [],
        values: [],
        modifyTime: '-',
      },
    ],
  },
  {
    categoryName: '用户属性',
    categoryType: 'attribute',
    itemList: [
      {
        label: '用户ID',
        name: '_user_id',
        value: 'new1203_mggt#app1#user#_user_id#string',
        description:
          '通过 setUserId(）API分配给用户的唯一ID,通常是您业务系统的用户ID',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'user',
        values: [],
        modifyTime: '2024-03-05 10:27:03',
      },
      {
        label: '首次访问时间戳',
        name: '_user_first_touch_timestamp',
        value: 'new1203_mggt#app1#user#_user_first_touch_timestamp#int',
        description:
          '用户首次打开应用程序或访问站点的时间（以毫秒为单位），每个事件的 user 对象的都包含此属性',
        metadataSource: 'Preset',
        valueType: 'int',
        category: 'user',
        values: [],
        modifyTime: '2024-03-05 10:27:03',
      },
      {
        label: '首次访问日期',
        name: '_first_visit_date',
        value: 'new1203_mggt#app1#user_outer#_first_visit_date#string',
        description: '用户首次打开应用程序或访问站点的日期',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'user_outer',
        values: [],
        modifyTime: '2024-03-05 10:27:03',
      },
      {
        label: '首次访问前序外链地址',
        name: '_first_referer',
        value: 'new1203_mggt#app1#user_outer#_first_referer#string',
        description: '用户第一次打开应用程序时的外链',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'user_outer',
        values: [],
        modifyTime: '2024-03-05 10:27:03',
      },
      {
        label: '首次访问流量来源类型',
        name: '_first_traffic_source_type',
        value: 'new1203_mggt#app1#user_outer#_first_traffic_source_type#string',
        description: '第一个捕获的流量源',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'user_outer',
        values: [],
        modifyTime: '2024-03-05 10:27:03',
      },
      {
        label: '首次访问流量媒介',
        name: '_first_traffic_medium',
        value: 'new1203_mggt#app1#user_outer#_first_traffic_medium#string',
        description: '第一个捕获的流量媒介',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'user_outer',
        values: [],
        modifyTime: '2024-03-05 10:27:03',
      },
      {
        label: '首次访问流量来源名称',
        name: '_first_traffic_source',
        value: 'new1203_mggt#app1#user_outer#_first_traffic_source#string',
        description: '第一个捕获的流量来源',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'user_outer',
        values: [],
        modifyTime: '2024-03-05 10:27:03',
      },
      {
        label: '首次访问安装来源',
        name: '_channel',
        value: 'new1203_mggt#app1#user_outer#_channel#string',
        description: '第一个捕获的渠道',
        metadataSource: 'Preset',
        valueType: 'string',
        category: 'user_outer',
        values: [],
        modifyTime: '2024-03-05 10:27:03',
      },
    ],
  },
];

export const MULTI_LEVEL_SELECT_OPTIONS: any = [
  {
    value: 'EVENT_CNT',
    label: '总次数',
  },
  {
    label: '按照...求和 (SUM)',
    value: 'SUM_VALUE',
    subList: [
      {
        value: '_session_start_timestamp',
        label: '会话开始时间戳',
        name: '_session_start_timestamp',
        valueType: 'int',
        category: 'event',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: '_session_duration',
        label: '会话时长(毫秒）',
        name: '_session_duration',
        valueType: 'int',
        category: 'event',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: '_session_number',
        label: '会话编号',
        name: '_session_number',
        valueType: 'int',
        category: 'event',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: 'event_timestamp',
        label: '事件时间戳',
        name: 'event_timestamp',
        valueType: 'int',
        category: 'other',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: 'event_value_in_usd',
        label: '事件价值（USD）',
        name: 'event_value_in_usd',
        valueType: 'float',
        category: 'other',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: 'time_zone_offset_seconds',
        label: '时差',
        name: 'time_zone_offset_seconds',
        valueType: 'int',
        category: 'device',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: 'screen_width',
        label: '屏幕宽度',
        name: 'screen_width',
        valueType: 'int',
        category: 'device',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: 'screen_height',
        label: '屏幕高度',
        name: 'screen_height',
        valueType: 'int',
        category: 'device',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: 'viewport_width',
        label: '视区宽度',
        name: 'viewport_width',
        valueType: 'int',
        category: 'device',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: 'viewport_height',
        label: '视区高度',
        name: 'viewport_height',
        valueType: 'int',
        category: 'device',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: 'latitude',
        label: '纬度',
        name: 'latitude',
        valueType: 'double',
        category: 'geo',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: 'longitude',
        label: '经度',
        name: 'longitude',
        valueType: 'double',
        category: 'geo',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: 'accuracy',
        label: '地址推测精度',
        name: 'accuracy',
        valueType: 'int',
        category: 'geo',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
      {
        value: '_user_first_touch_timestamp',
        label: '首次访问时间戳',
        name: '_user_first_touch_timestamp',
        valueType: 'int',
        category: 'user',
        groupName: 'SUM_VALUE',
        itemType: 'children',
      },
    ],
  },
];

// For segment selection

export const darkBackgroundColors = [
  '#033160',
  '#A82A0C',
  '#037F0C',
  '#1D3557',
  '#780000',
  '#0B3C5D',
  '#F13C20',
  '#343A40',
  '#10316B',
  '#8D0801',
];

enum ConditionType {
  USER_DONE = 'USER_DONE',
  USER_NOT_DONE = 'USER_NOT_DONE',
  USER_DONE_IN_SEQUENCE = 'USER_DONE_IN_SEQUENCE',
  USER_IS = 'USER_IS',
  USER_IS_NOT = 'USER_IS_NOT',
}

export const CONDITION_LIST: SelectProps.Option[] = [
  { label: 'User has done', value: ConditionType.USER_DONE },
  { label: 'The user has not done', value: ConditionType.USER_NOT_DONE },
  {
    label: 'User has done in sequence',
    value: ConditionType.USER_DONE_IN_SEQUENCE,
  },
  { label: 'User is', value: ConditionType.USER_IS },
  { label: 'User is not', value: ConditionType.USER_IS_NOT },
];

export const DEFAULT_SEGMENT_ITEM: IEventSegmentationItem = {
  userEventType: CONDITION_LIST[0],
  subItemList: [],
};

export const DEFAULT_FILTER_GROUP_ITEM: IEventSegmentationItem = {
  userEventType: CONDITION_LIST[0],
  conditionRelationShip: ERelationShip.OR,
  subItemList: [
    {
      userEventType: CONDITION_LIST[0],
      subItemList: [],
    },
    {
      userEventType: CONDITION_LIST[0],
      subItemList: [],
    },
  ],
  groupDateRange: 'a',
};

export const DEFAULT_SEGMENT_GROUP_DATA: IEventSegmentationObj = {
  conditionRelationShip: ERelationShip.AND,
  subItemList: [{ ...DEFAULT_FILTER_GROUP_ITEM }],
};
