CREATE OR REPLACE PROCEDURE {{schema}}.sp_merge_event_v2(manifestFileName varchar(65535), iam_role varchar(65535)) 
AS 
$$ 
DECLARE
	log_name varchar(50) := 'sp_merge_event_v2';
BEGIN
	CREATE temp TABLE event_v2_stage (like {{schema}}.event_v2);

	EXECUTE 'COPY event_v2_stage FROM ''' || manifestFileName || ''' IAM_ROLE ''' || iam_role || ''' STATUPDATE ON FORMAT AS PARQUET SERIALIZETOJSON MANIFEST ACCEPTINVCHARS'; 
	CALL {{schema}}.{{sp_clickstream_log}}(log_name, 'info', 'Copy ods data into event v2 stage table successfully.');

	MERGE INTO {{schema}}.event_v2
	USING event_v2_stage AS stage ON (
		{{schema}}.event_v2.event_id = stage.event_id AND 
		{{schema}}.event_v2.event_timestamp = stage.event_timestamp
	)	
	WHEN MATCHED THEN
		UPDATE SET 
				created_time = CURRENT_TIMESTAMP
	WHEN NOT MATCHED THEN
		INSERT (
				event_timestamp, 
				event_id, 
				event_time_msec, 
				event_name, 
				event_value, 
				event_value_currency, 
				event_bundle_sequence_id, 
				ingest_time_msec, 
				device_mobile_brand_name, 
				device_mobile_model_name,
				device_manufacturer,
				device_carrier,
				device_network_type,
				device_operating_system,
				device_operating_system_version,
				device_vendor_id,
				device_advertising_id,
				device_system_language,
				device_time_zone_offset_seconds,
				device_ua_browser,
				device_ua_browser_version,
				device_ua_os,
				device_ua_os_version,
				device_ua_device,
				device_ua_device_category,
				device_ua,
				device_screen_width,
				device_screen_height,
				device_viewport_width,
				device_viewport_height,
				geo_continent,
				geo_sub_continent,
				geo_country,
				geo_region,
				geo_metro,
				geo_city,
				geo_locale,
				traffic_source_source,
				traffic_source_medium,
				traffic_source_campaign,
				traffic_source_content,
				traffic_source_term,
				traffic_source_campaign_id,
				traffic_source_clid_platform,
				traffic_source_clid,
				traffic_source_channel_group,
				traffic_source_category,
				user_first_touch_time_msec,
				app_package_id,
				app_version,
				app_title,
				app_install_source,
				platform,
				project_id,
				app_id,
				screen_view_screen_name,
				screen_view_screen_id,
				screen_view_screen_unique_id,
				screen_view_previous_screen_name,
				screen_view_previous_screen_id,
				screen_view_previous_screen_unique_id,
				screen_view_previous_time_msec,
				screen_view_engagement_time_msec,
				screen_view_entrances,
				page_view_page_referrer,
				page_view_page_referrer_title,
				page_view_previous_time_msec,
				page_view_engagement_time_msec,
				page_view_page_title,
				page_view_page_url,
				page_view_page_url_path,
				page_view_page_url_query_parameters,
				page_view_hostname,
				page_view_latest_referrer,
				page_view_latest_referrer_host,
				page_view_entrances,
				app_start_is_first_time,
				upgrade_previous_app_version,
				upgrade_previous_os_version,
				search_key,
				search_term,
				outbound_link_classes,
				outbound_link_domain,
				outbound_link_id,
				outbound_link_url,
				outbound_link,
				user_engagement_time_msec,
				user_id,
				user_pseudo_id,
				session_id,
				session_start_time_msec,
				session_duration,
				session_number,
				scroll_engagement_time_msec,
				sdk_error_code,
				sdk_error_message,
				sdk_version,
				sdk_name,
				app_exception_message,
				app_exception_stack,
				custom_parameters_json_str,
				custom_parameters,
				process_info,
				created_time)
		VALUES (
				stage.event_timestamp, 
				stage.event_id, 
				stage.event_time_msec, 
				stage.event_name, 
				stage.event_value, 
				stage.event_value_currency, 
				stage.event_bundle_sequence_id, 
				stage.ingest_time_msec, 
				stage.device_mobile_brand_name, 
				stage.device_mobile_model_name,
				stage.device_manufacturer,
				stage.device_carrier,
				stage.device_network_type,
				stage.device_operating_system,
				stage.device_operating_system_version,
				stage.device_vendor_id,
				stage.device_advertising_id,
				stage.device_system_language,
				stage.device_time_zone_offset_seconds,
				stage.device_ua_browser,
				stage.device_ua_browser_version,
				stage.device_ua_os,
				stage.device_ua_os_version,
				stage.device_ua_device,
				stage.device_ua_device_category,
				stage.device_ua,
				stage.device_screen_width,
				stage.device_screen_height,
				stage.device_viewport_width,
				stage.device_viewport_height,
				stage.geo_continent,
				stage.geo_sub_continent,
				stage.geo_country,
				stage.geo_region,
				stage.geo_metro,
				stage.geo_city,
				stage.geo_locale,
				stage.traffic_source_source,
				stage.traffic_source_medium,
				stage.traffic_source_campaign,
				stage.traffic_source_content,
				stage.traffic_source_term,
				stage.traffic_source_campaign_id,
				stage.traffic_source_clid_platform,
				stage.traffic_source_clid,
				stage.traffic_source_channel_group,
				stage.traffic_source_category,
				stage.user_first_touch_time_msec,
				stage.app_package_id,
				stage.app_version,
				stage.app_title,
				stage.app_install_source,
				stage.platform,
				stage.project_id,
				stage.app_id,
				stage.screen_view_screen_name,
				stage.screen_view_screen_id,
				stage.screen_view_screen_unique_id,
				stage.screen_view_previous_screen_name,
				stage.screen_view_previous_screen_id,
				stage.screen_view_previous_screen_unique_id,
				stage.screen_view_previous_time_msec,
				stage.screen_view_engagement_time_msec,
				stage.screen_view_entrances,
				stage.page_view_page_referrer,
				stage.page_view_page_referrer_title,
				stage.page_view_previous_time_msec,
				stage.page_view_engagement_time_msec,
				stage.page_view_page_title,
				stage.page_view_page_url,
				stage.page_view_page_url_path,
				stage.page_view_page_url_query_parameters,
				stage.page_view_hostname,
				stage.page_view_latest_referrer,
				stage.page_view_latest_referrer_host,
				stage.page_view_entrances,
				stage.app_start_is_first_time,
				stage.upgrade_previous_app_version,
				stage.upgrade_previous_os_version,
				stage.search_key,
				stage.search_term,
				stage.outbound_link_classes,
				stage.outbound_link_domain,
				stage.outbound_link_id,
				stage.outbound_link_url,
				stage.outbound_link,
				stage.user_engagement_time_msec,
				stage.user_id,
				stage.user_pseudo_id,
				stage.session_id,
				stage.session_start_time_msec,
				stage.session_duration,
				stage.session_number,
				stage.scroll_engagement_time_msec,
				stage.sdk_error_code,
				stage.sdk_error_message,
				stage.sdk_version,
				stage.sdk_name,
				stage.app_exception_message,
				stage.app_exception_stack,
				stage.custom_parameters_json_str,
				stage.custom_parameters,
				stage.process_info,
				CURRENT_TIMESTAMP
		);
	CALL {{schema}}.{{sp_clickstream_log}}(log_name, 'info', 'Merge data into event v2 table successfully.');

	DROP TABLE event_v2_stage;
EXCEPTION WHEN OTHERS THEN
    CALL {{schema}}.{{sp_clickstream_log}}(log_name, 'error', 'error message:' || SQLERRM);	
END;
$$ LANGUAGE plpgsql;