name: source scan
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  git-secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install git-secrets
        run: |-
          sudo apt update
          sudo apt install -y git git-secrets
      - name: Git secrets scan
        run: |-
          git secrets --register-aws
          git secrets --scan
  license-check:
    name: license check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install license-header-checker
        run: |-
          mkdir -p /tmp/license-check
          curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash -s -- -b /tmp/license-check
      - name: Run license check
        env:
          LICENSE_FILE: /tmp/license-check/license-header.txt
        run: |-
          sed -n 1,12p .projenrc.js > $LICENSE_FILE && cat $LICENSE_FILE
          /tmp/license-check/license-header-checker -a -r -i node_modules,cdk.out,coverage $LICENSE_FILE . ts tsx js java
          ([[ -z `git status -s` ]] || (echo "Found files violdate with license header" && exit 1))
  viperlight:
    name: pre-build scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Pre-build scan
        run: |-
          curl https://viperlight-scanner.s3.us-east-1.amazonaws.com/latest/.viperlightrc -o .viperlightrc
          curl https://viperlight-scanner.s3.us-east-1.amazonaws.com/latest/codescan-funcs.sh -o codescan-funcs.sh
          curl https://viperlight-scanner.s3.us-east-1.amazonaws.com/latest/viperlight.zip -o viperlight.zip
          unzip -q viperlight.zip -d ../viperlight && rm viperlight.zip
          ./codescan-prebuild-custom.sh